export interface VenueRawItem {
  id: string;
  category: "baladas" | "restaurantes" | "moteis";
  name: string;
  tagline: string;
  genre?: "pagode" | "sertanejo" | "funk" | "forro" | "rock" | "eletronica";
  cuisine?: "kids" | "japonesa" | "churrascaria" | "italiano" | "hamburgueria";
  motelStyle?: "hidro" | "piscina" | "design" | "tematica" | "economica";
  subType: string;
  subTypeEmoji: string;
  neighborhood: string;
  address: string;
  lat: number;
  lng: number;
  image: string;
  gallery: string[];
  rating: number;
  reviewsCount: number;
  openToday: boolean;
  openHours: string;
  priceCategory: "free" | "low" | "medium" | "high";
  entryPrice: string;
  priceDescription: string;
  hasVipList: boolean;
  allowsReservation: boolean;
  hasKidsSpace?: boolean;
  isOpenBar?: boolean;
  isWomenFree?: boolean;
  hasParking?: boolean;
  hasHydro?: boolean;
  hasPool?: boolean;
  hasPrivateGarage?: boolean;
  periodHours?: string;
  isAfterHours?: boolean;
  closesAt?: string;
  whatsapp: string;
  instagram: string;
  highlight: string;
  tags: string[];
  lineup?: string[];
  menuHighlights?: string[];
  amenities: string[];
}

export const BALADAS_110: VenueRawItem[] = [
  {
    id: "balada-dedge",
    category: "baladas",
    name: "D-Edge",
    tagline: "Referência global em música eletrônica com design futurista premiado",
    genre: "eletronica",
    subType: "Club Underground & Techno",
    subTypeEmoji: "⚡",
    neighborhood: "Barra Funda",
    address: "Av. Mário de Andrade, 141 - Barra Funda, São Paulo - SP, 01156-001",
    lat: -23.5287,
    lng: -46.6632,
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1000&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80"
    ],
    rating: 4.8,
    reviewsCount: 3950,
    openToday: true,
    openHours: "Hoje das 23:00 às 07:00",
    priceCategory: "high",
    entryPrice: "R$ 80 a R$ 160",
    priceDescription: "Pista principal iluminada por faixas de LED 3D e rooftop com vista panorâmica",
    hasVipList: true,
    allowsReservation: true,
    hasParking: true,
    isAfterHours: true,
    closesAt: "07:00",
    whatsapp: "551136659500",
    instagram: "dedgesp",
    highlight: "Sistema de som Funktion-One e amanhecer imperdível no terraço aberto.",
    tags: ["Música Eletrônica", "Rooftop Amanhecer", "Sistema de Som Funktion-One", "After Hours", "DJs Internacionais"],
    lineup: ["23h Warmup House", "02h Headliner Techno", "05h Sunrise Rooftop Set"],
    amenities: ["pista_danca", "drinks", "rooftop", "after_madrugada"]
  },
  {
    id: "balada-villa-jk",
    category: "baladas",
    name: "Villa JK",
    tagline: "O ápice do sertanejo universitário com camarotes exclusivos e mega shows",
    genre: "sertanejo",
    subType: "Balada Sertaneja Premium",
    subTypeEmoji: "🤠",
    neighborhood: "Vila Olímpia",
    address: "R. Beira Rio, 116 - Vila Olímpia, São Paulo - SP, 04548-050",
    lat: -23.5939,
    lng: -46.6853,
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1000&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1541532713592-79a0317b6b77?auto=format&fit=crop&w=1000&q=80"
    ],
    rating: 4.7,
    reviewsCount: 2840,
    openToday: true,
    openHours: "Hoje das 22:00 às 06:00",
    priceCategory: "high",
    entryPrice: "R$ 60 a R$ 140",
    priceDescription: "Entrada com consumação ou camarotes com atendimento de garçom privativo",
    hasVipList: true,
    allowsReservation: true,
    hasParking: true,
    isAfterHours: true,
    closesAt: "06:00",
    whatsapp: "5511999912020",
    instagram: "villajk_",
    highlight: "Camarotes suspensos de luxo e as duplas sertanejas mais tocadas do Brasil.",
    tags: ["Sertanejo Universitário", "Camarotes VIP", "Open Format", "Gente Bonita"],
    lineup: ["22h DJ Residente", "00h30 Dupla Sertaneja Principal", "03h30 Funk & Trap"],
    amenities: ["pista_danca", "drinks", "vip_free", "after_madrugada"]
  },
  {
    id: "balada-quintal-moema",
    category: "baladas",
    name: "Quintal do Espeto Moema",
    tagline: "Roda de samba contagiante, espetinhos nobres e chopp trincando",
    genre: "pagode",
    subType: "Roda de Samba & Espetinhos",
    subTypeEmoji: "🪘",
    neighborhood: "Moema",
    address: "Av. dos Carinás, 520 - Moema, São Paulo - SP, 04086-010",
    lat: -23.6068,
    lng: -46.6669,
    image: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1000&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1000&q=80"
    ],
    rating: 4.7,
    reviewsCount: 5210,
    openToday: true,
    openHours: "Hoje das 18:00 às 01:00",
    priceCategory: "medium",
    entryPrice: "R$ 30 a R$ 60",
    priceDescription: "Espetinhos variados, caipirinhas artesanais e samba ao vivo",
    hasVipList: true,
    allowsReservation: true,
    hasParking: true,
    whatsapp: "551150956565",
    instagram: "quintaldoespeto",
    highlight: "Mais de 70 tipos de espetos na brasa com música ao vivo todos os dias.",
    tags: ["Roda de Samba", "Espetos na Brasa", "Chopp Gelado", "Música ao Vivo"],
    amenities: ["musica_ao_vivo", "chopp", "petiscos", "drinks"]
  },
  {
    id: "balada-quintal-vilamada",
    category: "baladas",
    name: "Quintal do Espeto Vila Madalena",
    tagline: "O ponto mais animado da Vila Madalena para curtir pagode em roda 360°",
    genre: "pagode",
    subType: "Roda de Samba & Cerveja Gelada",
    subTypeEmoji: "🪘",
    neighborhood: "Vila Madalena",
    address: "R. Mourato Coelho, 1022 - Pinheiros, São Paulo - SP, 05417-001",
    lat: -23.5583,
    lng: -46.6914,
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.6,
    reviewsCount: 4120,
    openToday: true,
    openHours: "Hoje das 18:00 às 02:00",
    priceCategory: "medium",
    entryPrice: "R$ 35 a R$ 65",
    priceDescription: "Ambiente descontraído com telões e banda ao vivo",
    hasVipList: true,
    allowsReservation: true,
    whatsapp: "551150956565",
    instagram: "quintaldoespeto",
    highlight: "Roda de samba no centro do salão com atendimento rápido de bebidas.",
    tags: ["Pagode ao Vivo", "Caipirinhas", "Vila Madalena", "Espetinhos"],
    amenities: ["musica_ao_vivo", "chopp", "petiscos", "drinks"]
  },
  {
    id: "balada-bar-templo",
    category: "baladas",
    name: "Bar Templo - Fé e Samba",
    tagline: "Templo do samba com mais de 500 imagens sacras e grandes baluartes",
    genre: "pagode",
    subType: "Samba Raiz & Religiosidade",
    subTypeEmoji: "🪘",
    neighborhood: "Mooca",
    address: "R. Guaimbé, 322 - Mooca, São Paulo - SP, 03118-030",
    lat: -23.5594,
    lng: -46.5986,
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.8,
    reviewsCount: 4680,
    openToday: true,
    openHours: "Hoje das 18:00 às 03:00",
    priceCategory: "medium",
    entryPrice: "R$ 40 a R$ 70",
    priceDescription: "Samba de primeira linha, feijoada e chopp artesanal",
    hasVipList: true,
    allowsReservation: true,
    whatsapp: "551132511200",
    instagram: "bartemplo",
    highlight: "Santuário cultural com energia indescritível e os maiores nomes do samba nacional.",
    tags: ["Samba Raiz", "Mooca Tradicional", "Chopp Artesanal", "Baluartes"],
    amenities: ["musica_ao_vivo", "chopp", "petiscos", "drinks"]
  },
  {
    id: "balada-carioca-club",
    category: "baladas",
    name: "Carioca Club Pinheiros",
    tagline: "A casa mais tradicional do pagode e funk paulistano desde 2002",
    genre: "pagode",
    subType: "Casa de Shows & Balada",
    subTypeEmoji: "🪘",
    neighborhood: "Pinheiros",
    address: "R. Cardeal Arcoverde, 2899 - Pinheiros, São Paulo - SP, 05407-004",
    lat: -23.5684,
    lng: -46.6975,
    image: "https://images.unsplash.com/photo-1545128485-c400e7702796?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1545128485-c400e7702796?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.6,
    reviewsCount: 6890,
    openToday: true,
    openHours: "Hoje das 22:00 às 05:00",
    isAfterHours: true,
    closesAt: "05:00",
    priceCategory: "medium",
    entryPrice: "R$ 35 a R$ 80",
    priceDescription: "Palco central de shows, camarotes suspensos e ampla pista",
    hasVipList: true,
    allowsReservation: true,
    isWomenFree: true,
    whatsapp: "551138135400",
    instagram: "cariocaclub",
    highlight: "Noites históricas com os maiores grupos de pagode dos anos 90 e da atualidade.",
    tags: ["Pagode 90", "Shows Nacionais", "Pista Gigante", "After Hours"],
    amenities: ["pista_danca", "musica_ao_vivo", "drinks", "chopp", "vip_free", "after_madrugada"]
  },
  {
    id: "balada-traco-de-uniao",
    category: "baladas",
    name: "Traço de União",
    tagline: "Samba autêntico de raiz e chorinho na beira do Largo da Batata",
    genre: "pagode",
    subType: "Samba Tradicional & Chorinho",
    subTypeEmoji: "🪘",
    neighborhood: "Pinheiros",
    address: "R. Cláudio Soares, 73 - Pinheiros, São Paulo - SP, 05422-030",
    lat: -23.5695,
    lng: -46.6958,
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.7,
    reviewsCount: 3120,
    openToday: true,
    openHours: "Hoje das 18:00 às 02:00",
    priceCategory: "medium",
    entryPrice: "R$ 35 a R$ 55",
    priceDescription: "Feijoada, cerveja gelada de garrafa e músicos renomados",
    hasVipList: true,
    allowsReservation: true,
    whatsapp: "551130316586",
    instagram: "tracodeuniao",
    highlight: "Ambiente boêmio genuíno com o melhor do samba de terreiro e de quadra.",
    tags: ["Samba de Raiz", "Largo da Batata", "Feijoada com Samba", "Chopp"],
    amenities: ["musica_ao_vivo", "chopp", "petiscos", "drinks"]
  },
  {
    id: "balada-coracao-sertanejo",
    category: "baladas",
    genre: "sertanejo",
    name: "Coração Sertanejo",
    tagline: "A maior balada sertaneja da Zona Sul com 2 palcos e touro mecânico",
    subType: "Mega Balada Sertaneja",
    subTypeEmoji: "🤠",
    neighborhood: "Interlagos",
    address: "Av. Atlântica, 4095 - Interlagos, São Paulo - SP, 04772-005",
    lat: -23.6892,
    lng: -46.7028,
    image: "https://images.unsplash.com/photo-1541532713592-79a0317b6b77?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1541532713592-79a0317b6b77?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.6,
    reviewsCount: 7850,
    openToday: true,
    openHours: "Hoje das 21:00 às 05:30",
    isAfterHours: true,
    closesAt: "05:30",
    priceCategory: "medium",
    entryPrice: "R$ 40 a R$ 90",
    priceDescription: "Dois palcos com bandas ao vivo simultâneas e camarote mezanino",
    hasVipList: true,
    allowsReservation: true,
    hasParking: true,
    whatsapp: "551156606215",
    instagram: "coracaosertanejo",
    highlight: "Atmosfera vibrante com touro mecânico e o melhor modão de viola até o amanhecer.",
    tags: ["Sertanejo Universitário", "Modão Raiz", "Touro Mecânico", "Interlagos"],
    amenities: ["pista_danca", "musica_ao_vivo", "drinks", "chopp", "after_madrugada"]
  },
  {
    id: "balada-villa-country",
    category: "baladas",
    genre: "sertanejo",
    name: "Villa Country",
    tagline: "O maior complexo temático country da América Latina com 12.000m²",
    subType: "Complexo Country & Shows",
    subTypeEmoji: "🤠",
    neighborhood: "Barra Funda",
    address: "Av. Francisco Matarazzo, 774 - Água Branca, São Paulo - SP, 05001-000",
    lat: -23.5284,
    lng: -46.6711,
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.7,
    reviewsCount: 15400,
    openToday: true,
    openHours: "Hoje das 20:00 às 05:00",
    isAfterHours: true,
    closesAt: "05:00",
    priceCategory: "high",
    entryPrice: "R$ 50 a R$ 120",
    priceDescription: "Saloon texano, restaurante tex-mex, praça de alimentação e arenas de show",
    hasVipList: true,
    allowsReservation: true,
    hasParking: true,
    whatsapp: "551138688200",
    instagram: "villacountry",
    highlight: "Cenário cinematográfico do velho oeste onde os maiores ícones sertanejos se apresentam.",
    tags: ["Velho Oeste", "Super Estrutura", "Shows Nacionais", "Restaurante Country"],
    amenities: ["pista_danca", "musica_ao_vivo", "drinks", "chopp", "petiscos", "after_madrugada"]
  },
  {
    id: "balada-lions-nightclub",
    category: "baladas",
    genre: "eletronica",
    name: "Lions Nightclub",
    tagline: "Varanda suspensa com vista da Catedral da Sé e pista 3D iluminada",
    subType: "Club Sofisticado & Pista 3D",
    subTypeEmoji: "⚡",
    neighborhood: "Centro Histórico",
    address: "Av. Brigadeiro Luís Antônio, 277 - Bela Vista, São Paulo - SP, 01317-000",
    lat: -23.5518,
    lng: -46.6385,
    image: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.6,
    reviewsCount: 2950,
    openToday: true,
    openHours: "Hoje das 23:00 às 06:00",
    isAfterHours: true,
    closesAt: "06:00",
    priceCategory: "medium",
    entryPrice: "R$ 50 a R$ 110",
    priceDescription: "Pista quadriculada com luzes dinâmicas e varanda externa com vista do centro",
    hasVipList: true,
    allowsReservation: true,
    whatsapp: "551131046711",
    instagram: "lionsnightclub",
    highlight: "Curadoria musical de house e disco music em ambiente sofisticado.",
    tags: ["Varanda Panorâmica", "Pista 3D", "House & Disco", "Centro Histórico"],
    amenities: ["pista_danca", "drinks", "rooftop", "after_madrugada"]
  },
  {
    id: "balada-tokyo-sp",
    category: "baladas",
    genre: "eletronica",
    name: "Tokyo SP",
    tagline: "Prédio modernista de 9 andares com karaokê privativo e rooftop com vista pro Copan",
    subType: "Prédio Cultural, Karaokê & Rooftop",
    subTypeEmoji: "⚡",
    neighborhood: "República",
    address: "R. Major Sertório, 110 - Vila Buarque, São Paulo - SP, 01222-000",
    lat: -23.5469,
    lng: -46.6457,
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.7,
    reviewsCount: 6300,
    openToday: true,
    openHours: "Hoje das 18:00 às 05:00",
    isAfterHours: true,
    closesAt: "05:00",
    priceCategory: "medium",
    entryPrice: "R$ 45 a R$ 90",
    priceDescription: "Acesso aos 9 andares, salas de karaokê temáticas e balada na cobertura",
    hasVipList: true,
    allowsReservation: true,
    whatsapp: "551131590740",
    instagram: "tokyosp",
    highlight: "Vista de tirar o fôlego dos arranha-céus paulistanos e karaokês inspirados em Tóquio.",
    tags: ["Rooftop Copan", "Karaokê Box", "Culinária Oriental", "Pop & Indie"],
    amenities: ["karaoke", "pista_danca", "drinks", "rooftop", "after_madrugada"]
  },
  {
    id: "balada-audio-club",
    category: "baladas",
    genre: "funk",
    name: "Audio Club",
    tagline: "Mega espaço de shows com sistema acústico de arena e os maiores bailes funk do país",
    subType: "Mega Club & Espaço de Shows",
    subTypeEmoji: "🔊",
    neighborhood: "Barra Funda",
    address: "Av. Francisco Matarazzo, 694 - Água Branca, São Paulo - SP, 05001-000",
    lat: -23.5281,
    lng: -46.6698,
    image: "https://images.unsplash.com/photo-1545128485-c400e7702796?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1545128485-c400e7702796?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.7,
    reviewsCount: 8900,
    openToday: true,
    openHours: "Hoje das 22:00 às 06:00",
    isAfterHours: true,
    closesAt: "06:00",
    priceCategory: "high",
    entryPrice: "R$ 60 a R$ 150",
    priceDescription: "Capacidade para mais de 3.000 pessoas com camarotes e área VIP",
    hasVipList: true,
    allowsReservation: true,
    hasParking: true,
    whatsapp: "551138628279",
    instagram: "audiosp",
    highlight: "Palco de turnês históricas de funk, trap, rap e música eletrônica nacional.",
    tags: ["Baile Funk", "Mega Shows", "Trap & Hip Hop", "Grave Pesado"],
    amenities: ["pista_danca", "musica_ao_vivo", "drinks", "after_madrugada"]
  },
  {
    id: "balada-cine-joia",
    category: "baladas",
    genre: "rock",
    name: "Cine Joia",
    tagline: "Cinema histórico dos anos 50 com projeção mapeada 360° e shows inesquecíveis",
    subType: "Antigo Cinema & Projeção 360°",
    subTypeEmoji: "🎸",
    neighborhood: "Liberdade",
    address: "Praça Carlos Gomes, 82 - Sé, São Paulo - SP, 01507-000",
    lat: -23.5539,
    lng: -46.6342,
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.7,
    reviewsCount: 7100,
    openToday: true,
    openHours: "Hoje das 22:00 às 05:00",
    isAfterHours: true,
    closesAt: "05:00",
    priceCategory: "high",
    entryPrice: "R$ 50 a R$ 120",
    priceDescription: "Acústica fantástica e bar com drinks clássicos",
    hasVipList: true,
    allowsReservation: true,
    whatsapp: "551131011305",
    instagram: "cinejoia",
    highlight: "Imersão visual completa com projeções de alta tecnologia em todo o domo.",
    tags: ["Cinema Histórico", "Projeção Mapeada 360", "Indie Rock", "Shows Intimistas"],
    amenities: ["pista_danca", "musica_ao_vivo", "drinks", "chopp", "after_madrugada"]
  },
  {
    id: "balada-morrison-rock-bar",
    category: "baladas",
    genre: "rock",
    name: "Morrison Rock Bar",
    tagline: "Mais de 25 anos celebrando os clássicos do rock com bandas tributo impecáveis",
    subType: "Classic Rock & Tributos",
    subTypeEmoji: "🎸",
    neighborhood: "Vila Madalena",
    address: "R. Fidalga, 531 - Vila Madalena, São Paulo - SP, 05432-070",
    lat: -23.5541,
    lng: -46.6908,
    image: "https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.8,
    reviewsCount: 5400,
    openToday: true,
    openHours: "Hoje das 20:00 às 04:30",
    closesAt: "04:30",
    priceCategory: "medium",
    entryPrice: "R$ 35 a R$ 60",
    priceDescription: "Bandas covers de Led Zeppelin, Queen, Pink Floyd e AC/DC",
    hasVipList: true,
    allowsReservation: true,
    whatsapp: "551138149671",
    instagram: "morrisonrockbar",
    highlight: "Clima autêntico de pub de rock com chopp artesanal e público apaixonado.",
    tags: ["Classic Rock", "Bandas Tributo", "Vila Madalena", "Chopp Artesanal"],
    amenities: ["musica_ao_vivo", "chopp", "petiscos", "drinks"]
  },
  {
    id: "balada-manifesto-bar",
    category: "baladas",
    genre: "rock",
    name: "Manifesto Rock Bar",
    tagline: "O ponto de encontro das lendas do heavy metal e hard rock mundial em São Paulo",
    subType: "Heavy Metal & Hard Rock",
    subTypeEmoji: "🎸",
    neighborhood: "Itaim Bibi",
    address: "R. Iguatemi, 36 - Itaim Bibi, São Paulo - SP, 04531-010",
    lat: -23.5831,
    lng: -46.6802,
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.7,
    reviewsCount: 3820,
    openToday: true,
    openHours: "Hoje das 20:00 às 05:00",
    isAfterHours: true,
    closesAt: "05:00",
    priceCategory: "medium",
    entryPrice: "R$ 40 a R$ 75",
    priceDescription: "Guitarras históricas autografadas por astros do Iron Maiden, Scorpions e Kiss",
    hasVipList: true,
    allowsReservation: true,
    whatsapp: "551131689595",
    instagram: "manifestobar",
    highlight: "Ambiente repleto de relíquias do rock e palco consagrado para bandas pesadas.",
    tags: ["Hard Rock", "Heavy Metal", "Guitarras Históricas", "Itaim Noturno"],
    amenities: ["musica_ao_vivo", "chopp", "drinks", "after_madrugada"]
  },
  {
    id: "balada-canto-da-ema",
    category: "baladas",
    genre: "forro",
    name: "Canto da Ema",
    tagline: "A catedral do forró pé de serra paulistano: sanfona, zabumba e triângulo ao vivo",
    subType: "Forró Pé de Serra Autêntico",
    subTypeEmoji: "🪗",
    neighborhood: "Pinheiros",
    address: "Av. Brg. Faria Lima, 364 - Pinheiros, São Paulo - SP, 05426-200",
    lat: -23.5658,
    lng: -46.6948,
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.8,
    reviewsCount: 3900,
    openToday: true,
    openHours: "Hoje das 20:30 às 03:00",
    priceCategory: "medium",
    entryPrice: "R$ 35 a R$ 55",
    priceDescription: "Pista ampla para dançar xote e baião com chopp gelado",
    hasVipList: true,
    allowsReservation: true,
    whatsapp: "551138134708",
    instagram: "cantodaema",
    highlight: "Espaço consagrado que reúne os maiores mestres da sanfona e apaixonados pela dança.",
    tags: ["Forró Pé de Serra", "Dança de Salão", "Sanfona ao Vivo", "Xote"],
    amenities: ["pista_danca", "musica_ao_vivo", "drinks", "chopp"]
  },
  {
    id: "balada-ctn-nordestinas",
    category: "baladas",
    genre: "forro",
    name: "CTN - Centro de Tradições Nordestinas",
    tagline: "O maior centro de cultura e gastronomia nordestina fora do Nordeste",
    subType: "Complexo Cultural, Forró & Piseiro",
    subTypeEmoji: "🪗",
    neighborhood: "Bairro do Limão",
    address: "R. Jacofer, 615 - Bairro do Limão, São Paulo - SP, 02712-070",
    lat: -23.5042,
    lng: -46.6789,
    image: "https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.8,
    reviewsCount: 42000,
    openToday: true,
    openHours: "Hoje das 11:00 às 05:00",
    isAfterHours: true,
    closesAt: "05:00",
    priceCategory: "medium",
    entryPrice: "Entrada Franca ou Shows R$ 40 a R$ 100",
    priceDescription: "Restaurantes com carne de sol e baião, arena de shows para 10 mil pessoas",
    hasVipList: true,
    allowsReservation: true,
    hasParking: true,
    whatsapp: "551134889797",
    instagram: "ctnsp",
    highlight: "Grandes shows de piseiro, forró das antigas e culinária sertaneja completa.",
    tags: ["Cultura Nordestina", "Mega Espaço", "Carne de Sol", "Piseiro & Forró"],
    amenities: ["pista_danca", "musica_ao_vivo", "chopp", "petiscos", "after_madrugada"]
  },
  {
    id: "balada-alo-madrugada",
    category: "baladas",
    genre: "eletronica",
    name: "Alô Madrugada After Club",
    tagline: "O refúgio oficial dos inimigos do fim com DJs afiados das 05h às 13h",
    subType: "After Hours Clássico (05h às 13h)",
    subTypeEmoji: "🌙",
    neighborhood: "Santa Cecília",
    address: "R. Frederico Abranches, 189 - Santa Cecília, São Paulo - SP, 01225-000",
    lat: -23.5385,
    lng: -46.6508,
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.7,
    reviewsCount: 1650,
    openToday: true,
    openHours: "Hoje das 05:00 às 13:00",
    isAfterHours: true,
    closesAt: "13:00",
    priceCategory: "medium",
    entryPrice: "R$ 50 a R$ 90",
    priceDescription: "Pista climatizada, área lounge com sofás e café da manhã especial",
    hasVipList: true,
    allowsReservation: true,
    whatsapp: "5511988887711",
    instagram: "alomadrugadaafter",
    highlight: "A balada não para: line-up de tech house e techno para prolongar o final de semana.",
    tags: ["After 05h", "Techno & House", "Madrugada Prolongada", "Lounge"],
    amenities: ["pista_danca", "drinks", "after_madrugada"]
  }
];

// Gerador dinâmico dos estabelecimentos complementares de baladas reais de SP
const REAL_BALADAS_EXTRA = [
  { name: "Heavy House", neighborhood: "Pinheiros", address: "R. Benjamim Egas, 297", lat: -23.5598, lng: -46.6887, insta: "heavyhouse", genre: "eletronica", type: "Club Intimista & House", price: "R$ 40 a R$ 80" },
  { name: "Zig Club", neighborhood: "Bela Vista", address: "R. Álvaro de Carvalho, 267", lat: -23.5489, lng: -46.6432, insta: "zig_club", genre: "funk", type: "Club Pop & Alternativo", price: "R$ 30 a R$ 60" },
  { name: "Fabrique Club", neighborhood: "Barra Funda", address: "R. Barra Funda, 1071", lat: -23.5255, lng: -46.6578, insta: "fabrique.club", genre: "eletronica", type: "Galpão Industrial & Techno", price: "R$ 50 a R$ 120" },
  { name: "Madame Underground Club", neighborhood: "Bela Vista", address: "R. Conselheiro Ramalho, 873", lat: -23.5582, lng: -46.6438, insta: "madameclub", genre: "rock", type: "Templo Gótico & Darkwave", price: "R$ 35 a R$ 70" },
  { name: "Nitro Night", neighborhood: "Interlagos", address: "R. Marcolino Pais do Amaral, 51", lat: -23.6821, lng: -46.7011, insta: "nitronight", genre: "funk", type: "Paredão de Funk & Trap", price: "R$ 30 a R$ 70" },
  { name: "Vitrini Lounge SP", neighborhood: "Itaim Bibi", address: "R. Canário, 544", lat: -23.5852, lng: -46.6789, insta: "vitrinilounge.sp", genre: "funk", type: "Lounge VIP & Funk Chic", price: "R$ 60 a R$ 140" },
  { name: "Love Cabaret", neighborhood: "República", address: "R. Araújo, 232", lat: -23.5458, lng: -46.6475, insta: "lovecabaretsp", genre: "eletronica", type: "Parque Erótico & Performances", price: "R$ 70 a R$ 180" },
  { name: "Tetto Rooftop Lounge", neighborhood: "Jardins", address: "Av. Rebouças, 955 - Cobertura", lat: -23.5621, lng: -46.6712, insta: "tettolounge", genre: "eletronica", type: "Rooftop Sofisticado & Drinks", price: "R$ 80 a R$ 200" },
  { name: "Beco 203", neighborhood: "Consolação", address: "R. Augusta, 609", lat: -23.5512, lng: -46.6514, insta: "beco203", genre: "rock", type: "Indie Rock & Open Bar", price: "R$ 40 a R$ 90" },
  { name: "The Blue Pub", neighborhood: "Bela Vista", address: "Alameda Ribeirão Preto, 384", lat: -23.5619, lng: -46.6534, insta: "thebluepub", genre: "rock", type: "Pub Inglês Tradicional", price: "R$ 30 a R$ 55" },
  { name: "O'Malley's Irish Pub", neighborhood: "Jardins", address: "Alameda Itu, 1529", lat: -23.5611, lng: -46.6672, insta: "omalleysbar", genre: "rock", type: "Irish Pub & Esportes", price: "R$ 35 a R$ 60" },
  { name: "Finnegan's Pub", neighborhood: "Pinheiros", address: "R. Cristiano Viana, 538", lat: -23.5562, lng: -46.6804, insta: "finneganspub", genre: "rock", type: "Irish Pub Clássico", price: "R$ 30 a R$ 50" },
  { name: "St. John's Irish Pub", neighborhood: "Tatuapé", address: "R. Itapura, 1308", lat: -23.5412, lng: -46.5689, insta: "stjohnspub", genre: "rock", type: "Pub Irlandês Zona Leste", price: "R$ 30 a R$ 55" },
  { name: "Willi Willie Bar e Arqueria", neighborhood: "Moema", address: "Alameda dos Pamaris, 30", lat: -23.6089, lng: -46.6612, insta: "williwilliebar", genre: "rock", type: "Rock Bar & Tiro com Arco", price: "R$ 30 a R$ 50" },
  { name: "Atlanta Snooker Bar", neighborhood: "Pinheiros", address: "R. Brg. Faria Lima, 543", lat: -23.5678, lng: -46.6932, insta: "atlantasnookerbar", genre: "sertanejo", type: "Sinuca Profissional & Bar", price: "R$ 25 a R$ 50" },
  { name: "Snooker Rock Bar", neighborhood: "Santana", address: "Av. Braz Leme, 1200", lat: -23.5089, lng: -46.6432, insta: "snookerrockbar", genre: "rock", type: "Sinuca, Rock & Chopp", price: "R$ 25 a R$ 45" },
  { name: "Hookah Star Lounge", neighborhood: "Tatuapé", address: "R. Serra de Bragança, 780", lat: -23.5398, lng: -46.5621, insta: "hookahstarlounge", genre: "funk", type: "Tabacaria & Lounge Hookah", price: "R$ 30 a R$ 60" },
  { name: "Lord Snooker Lounge", neighborhood: "Mooca", address: "R. da Mooca, 3120", lat: -23.5543, lng: -46.5921, insta: "lordsnooker", genre: "pagode", type: "Mesas Oficiais & Porções", price: "R$ 20 a R$ 40" },
  { name: "Vegas Snooker Bar", neighborhood: "Ipiranga", address: "R. Silva Bueno, 1850", lat: -23.5932, lng: -46.6012, insta: "vegassnooker", genre: "sertanejo", type: "Sinuca, Porções & Cerveja", price: "R$ 20 a R$ 45" },
  { name: "High Line Bar", neighborhood: "Vila Madalena", address: "R. Girassol, 144", lat: -23.5532, lng: -46.6892, insta: "highlinebar", genre: "eletronica", type: "Rooftop & Balada Estilosa", price: "R$ 50 a R$ 120" },
  { name: "Bar Brahma", neighborhood: "Centro Histórico", address: "Av. São João, 677", lat: -23.5418, lng: -46.6412, insta: "barbrahma", genre: "pagode", type: "MPB, Samba & Chopp Lendário", price: "R$ 40 a R$ 85" },
  { name: "The Secret After", neighborhood: "Barra Funda", address: "R. Cruzeiro, 450", lat: -23.5245, lng: -46.6542, insta: "thesecretaftersp", genre: "eletronica", type: "After Hours Underground", price: "R$ 50 a R$ 90" },
  { name: "Sunrise Rooftop After", neighborhood: "Centro Histórico", address: "R. Direita, 250 - Cobertura", lat: -23.5492, lng: -46.6348, insta: "sunriserooftop", genre: "eletronica", type: "After Amanhecer no Topo", price: "R$ 60 a R$ 100" },
  { name: "Galpão 5h Sunrise", neighborhood: "Mooca", address: "R. Borges de Figueiredo, 1100", lat: -23.5521, lng: -46.6021, insta: "galpaosunrise", genre: "eletronica", type: "Galpão After Industrial", price: "R$ 45 a R$ 80" },
  { name: "Komplexo Tempo", neighborhood: "Mooca", address: "Av. Henry Ford, 511", lat: -23.5689, lng: -46.5982, insta: "komplexotempo", genre: "eletronica", type: "Mega Club Ferroviário & Arte", price: "R$ 70 a R$ 160" },
  { name: "Green Valley SP Tour", neighborhood: "Vila Leopoldina", address: "Av. Manuel Bandeira, 360", lat: -23.5312, lng: -46.7321, insta: "greenvalleysp", genre: "eletronica", type: "EDM Festival Experience", price: "R$ 80 a R$ 180" },
  { name: "Sonora Underground Club", neighborhood: "Barra Funda", address: "R. Sérgio Tomás, 310", lat: -23.5212, lng: -46.6498, insta: "sonoraclubsp", genre: "eletronica", type: "Techno Escuro & Graves", price: "R$ 40 a R$ 80" },
  { name: "Bar Secreto", neighborhood: "Pinheiros", address: "R. Álvaro Anes, 97", lat: -23.5642, lng: -46.6912, insta: "barsecreto", genre: "eletronica", type: "Speakeasy Club Secreto", price: "R$ 50 a R$ 100" },
  { name: "Trabuca Bar Itaim", neighborhood: "Itaim Bibi", address: "Av. Pres. Juscelino Kubitschek, 1444", lat: -23.5892, lng: -46.6812, insta: "trabucabar", genre: "eletronica", type: "Alta Coquetelaria & Balada", price: "R$ 60 a R$ 150" },
  { name: "Trabuca Bar JK", neighborhood: "Vila Olímpia", address: "Av. Juscelino Kubitschek, 1800", lat: -23.5912, lng: -46.6854, insta: "trabucabar", genre: "eletronica", type: "Lounge Chic & DJs", price: "R$ 60 a R$ 140" },
  { name: "Tatu Bola Bar Itaim", neighborhood: "Itaim Bibi", address: "R. Clodomiro Amazonas, 202", lat: -23.5878, lng: -46.6792, insta: "tatubolabar", genre: "pagode", type: "Fitinhas do Bonfim & Pagode", price: "R$ 35 a R$ 75" },
  { name: "Tatu Bola Bar Vila Madalena", neighborhood: "Vila Madalena", address: "R. Mourato Coelho, 1450", lat: -23.5592, lng: -46.6954, insta: "tatubolabar", genre: "pagode", type: "Samba ao Vivo & Caipirinhas", price: "R$ 35 a R$ 75" },
  { name: "Tatu Bola Bar Jardins", neighborhood: "Jardins", address: "R. Augusta, 3000", lat: -23.5645, lng: -46.6689, insta: "tatubolabar", genre: "sertanejo", type: "Sertanejo Acústico & Chopp", price: "R$ 40 a R$ 80" },
  { name: "Eu Tu Eles Bar Faria Lima", neighborhood: "Itaim Bibi", address: "Av. Brg. Faria Lima, 2902", lat: -23.5812, lng: -46.6832, insta: "eutuelesbar", genre: "pagode", type: "Happy Hour Animado & Roda", price: "R$ 35 a R$ 70" },
  { name: "Eu Tu Eles Bar Vila Olímpia", neighborhood: "Vila Olímpia", address: "R. Gomes de Carvalho, 1575", lat: -23.5982, lng: -46.6842, insta: "eutuelesbar", genre: "sertanejo", type: "Sertanejo & Chopp Gelado", price: "R$ 35 a R$ 70" },
  { name: "Charles Edward", neighborhood: "Itaim Bibi", address: "R. Miriti, s/n - Itaim Bibi", lat: -23.5842, lng: -46.6798, insta: "barcharlesedward", genre: "rock", type: "Classic Rock & Paquera", price: "R$ 45 a R$ 90" },
  { name: "Kia Ora Pub", neighborhood: "Itaim Bibi", address: "R. Dr. Eduardo de Souza Aranha, 377", lat: -23.5872, lng: -46.6762, insta: "kiaorapub", genre: "rock", type: "Pub Australiano & Bandas", price: "R$ 35 a R$ 70" },
  { name: "Gràcia Bar", neighborhood: "Pinheiros", address: "R. Coropés, 87", lat: -23.5682, lng: -46.6982, insta: "graciabar", genre: "eletronica", type: "Tapas Espanholas & Pista", price: "R$ 40 a R$ 80" },
  { name: "Posto 6", neighborhood: "Vila Madalena", address: "R. Aspicuelta, 644", lat: -23.5548, lng: -46.6912, insta: "barposto6", genre: "pagode", type: "Boteco Carioca & Samba", price: "R$ 30 a R$ 60" },
  { name: "Bar Astor", neighborhood: "Vila Madalena", address: "R. Delfina, 163", lat: -23.5539, lng: -46.6898, insta: "barastor", genre: "rock", type: "Boemia Clássica & Chope", price: "R$ 40 a R$ 80" },
  { name: "SubAstor", neighborhood: "Vila Madalena", address: "R. Delfina, 163 - Subsolo", lat: -23.5539, lng: -46.6898, insta: "subastor", genre: "eletronica", type: "Speakeasy Subterrâneo & Drinks", price: "R$ 50 a R$ 110" },
  { name: "Olívio Bar", neighborhood: "Pinheiros", address: "R. Delfina, 196", lat: -23.5542, lng: -46.6902, insta: "oliviobar", genre: "eletronica", type: "Drinks Cenográficos & DJs", price: "R$ 45 a R$ 95" },
  { name: "Santo Cupido Bar", neighborhood: "Vila Nova Conceição", address: "R. Alvorada, 1951", lat: -23.5998, lng: -46.6821, insta: "santocupidobar", genre: "funk", type: "Lounge Romântico & Pista", price: "R$ 50 a R$ 120" },
  { name: "Club Jerome", neighborhood: "Higienópolis", address: "R. Mato Grosso, 398", lat: -23.5482, lng: -46.6572, insta: "clubjerome", genre: "eletronica", type: "House Clássica & Glamour", price: "R$ 50 a R$ 100" },
  { name: "Caos Bar & Club", neighborhood: "Consolação", address: "R. Augusta, 584", lat: -23.5508, lng: -46.6508, insta: "caosaugusta", genre: "rock", type: "Antiquário de Dia, Balada à Noite", price: "R$ 30 a R$ 60" },
  { name: "Club Yacht", neighborhood: "Bela Vista", address: "R. Treze de Maio, 703", lat: -23.5562, lng: -46.6478, insta: "clubyacht", genre: "eletronica", type: "Decoração Náutica & Pop", price: "R$ 40 a R$ 80" },
  { name: "Over Night Club", neighborhood: "Vila Olímpia", address: "R. Gomes de Carvalho, 799", lat: -23.5954, lng: -46.6812, insta: "overnightclub", genre: "eletronica", type: "Flashback 80/90 & Disco", price: "R$ 50 a R$ 100" },
  { name: "Bar das Patroas", neighborhood: "Itaim Bibi", address: "R. Tabapuã, 1410", lat: -23.5854, lng: -46.6812, insta: "bardaspatroassp", genre: "sertanejo", type: "Balada Sertaneja Feminina", price: "R$ 40 a R$ 90" },
  { name: "Bulls Club", neighborhood: "Tatuapé", address: "R. Salim Farah Maluf, 221", lat: -23.5389, lng: -46.5712, insta: "bullsclub", genre: "sertanejo", type: "Super Sertanejo Zona Leste", price: "R$ 40 a R$ 85" },
  { name: "Arena Sertaneja", neighborhood: "Penha", address: "Av. Amador Bueno da Veiga, 1312", lat: -23.5234, lng: -46.5412, insta: "arenasertanejasp", genre: "sertanejo", type: "Arena de Grandes Shows", price: "R$ 35 a R$ 80" },
  { name: "Wood's SP", neighborhood: "Vila Olímpia", address: "R. Quatá, 1016", lat: -23.5978, lng: -46.6819, insta: "woods_sp", genre: "sertanejo", type: "Grife Sertaneja Universitária", price: "R$ 60 a R$ 130" },
  { name: "Rancho do Serjão", neighborhood: "Moema", address: "Av. Pedroso de Morais, 1003", lat: -23.5612, lng: -46.6982, insta: "ranchodoserjao", genre: "sertanejo", type: "Costela na Brasa & Viola", price: "R$ 40 a R$ 80" },
  { name: "Boteco Todos os Santos", neighborhood: "Vila Madalena", address: "R. Aspicuelta, 585", lat: -23.5542, lng: -46.6918, insta: "botecotodosossantos", genre: "pagode", type: "Roda de Samba & Clima Festeiro", price: "R$ 30 a R$ 60" },
  { name: "Vila do Samba", neighborhood: "Casa Verde", address: "R. João Rudge, 340", lat: -23.5121, lng: -46.6542, insta: "viladosambaoficial", genre: "pagode", type: "Terreiro Tradicional de Samba", price: "R$ 30 a R$ 55" },
  { name: "Samba da Vela", neighborhood: "Santo Amaro", address: "Praça Ramos de Azevedo, 132", lat: -23.6512, lng: -46.7089, insta: "sambadavela", genre: "pagode", type: "Compositores & Velha Guarda", price: "R$ 20 a R$ 40" },
  { name: "Terra Brasilis Samba", neighborhood: "Tatuapé", address: "R. Serra de Bragança, 1024", lat: -23.5418, lng: -46.5642, insta: "terrabrasilissamba", genre: "pagode", type: "Pagode de Mesa & Chopp", price: "R$ 25 a R$ 50" },
  { name: "Quintal do Zeca Pagodinho", neighborhood: "Itaim Bibi", address: "Av. Juscelino Kubitschek, 1726", lat: -23.5902, lng: -46.6848, insta: "quintalzaozeca", genre: "pagode", type: "Chancelado pelo Mestre do Samba", price: "R$ 40 a R$ 80" },
  { name: "Quintal do Espeto Alto da Lapa", neighborhood: "Lapa", address: "R. Dr. José Elias, 547", lat: -23.5289, lng: -46.7092, insta: "quintaldoespeto", genre: "pagode", type: "Espetos Nobres & Samba", price: "R$ 30 a R$ 60" },
  { name: "Quintal do Espeto Tatuapé", neighborhood: "Tatuapé", address: "R. Serra de Botucatu, 1933", lat: -23.5432, lng: -46.5598, insta: "quintaldoespeto", genre: "pagode", type: "Amplo Espaço Verde & Pagode", price: "R$ 30 a R$ 60" },
  { name: "Quintal do Espeto Santana", neighborhood: "Santana", address: "Av. Ataliba Leonel, 1239", lat: -23.5012, lng: -46.6212, insta: "quintaldoespeto", genre: "pagode", type: "Samba ao Vivo na Zona Norte", price: "R$ 30 a R$ 60" },
  { name: "Quintal do Espeto Perdizes", neighborhood: "Perdizes", address: "R. Palestra Itália, 1200", lat: -23.5298, lng: -46.6789, insta: "quintaldoespeto", genre: "pagode", type: "Perto do Allianz Parque", price: "R$ 30 a R$ 60" },
  { name: "Quintal do Espeto Chácara Santo Antônio", neighborhood: "Santo Amaro", address: "R. Alexandre Dumas, 800", lat: -23.6312, lng: -46.7012, insta: "quintaldoespeto", genre: "pagode", type: "Happy Hour Empresarial & Samba", price: "R$ 30 a R$ 60" },
  { name: "Black White Club", neighborhood: "Tatuapé", address: "R. Emília Marengo, 400", lat: -23.5478, lng: -46.5612, insta: "blackwhiteclub", genre: "funk", type: "Funk & Sertanejo Universitário", price: "R$ 35 a R$ 70" },
  { name: "Galleria Bar", neighborhood: "Itaim Bibi", address: "R. Tabapuã, 1463", lat: -23.5849, lng: -46.6808, insta: "galleriabar", genre: "eletronica", type: "Arte Contemporânea & Balada", price: "R$ 50 a R$ 110" },
  { name: "Royal Club Classic", neighborhood: "Vila Olímpia", address: "R. Quatá, 460", lat: -23.5962, lng: -46.6802, insta: "royalcluboficial", genre: "funk", type: "Hip Hop, Trap & Camarotes", price: "R$ 60 a R$ 140" },
  { name: "Club Hotel Cambridge", neighborhood: "Centro Histórico", address: "R. Álvaro de Carvalho, 35", lat: -23.5482, lng: -46.6452, insta: "hotelcambridgeclub", genre: "rock", type: "Balada Subterrânea & Histórica", price: "R$ 30 a R$ 60" },
  { name: "Lions Terrace Club", neighborhood: "Bela Vista", address: "Av. Brigadeiro Luís Antônio, 285", lat: -23.5519, lng: -46.6387, insta: "lionsterrace", genre: "eletronica", type: "Terraço Open Air & Deep House", price: "R$ 45 a R$ 90" },
  { name: "Sirena SP Tour", neighborhood: "Morumbi", address: "Av. Giovanni Gronchi, 5000", lat: -23.6212, lng: -46.7289, insta: "sirenatursp", genre: "eletronica", type: "House Music de Maresias na Capital", price: "R$ 80 a R$ 180" },
  { name: "Dama Club", neighborhood: "Santo Amaro", address: "Av. João Dias, 1600", lat: -23.6421, lng: -46.7112, insta: "damaclubsp", genre: "pagode", type: "Samba, Pagode & Paquera", price: "R$ 30 a R$ 60" },
  { name: "Bamboa Club SP", neighborhood: "Tatuapé", address: "R. Cantagalo, 800", lat: -23.5398, lng: -46.5682, insta: "bamboaclubsp", genre: "sertanejo", type: "Sertanejo & Piseiro na Leste", price: "R$ 35 a R$ 75" },
  { name: "Mansão Sertaneja", neighborhood: "Tatuapé", address: "R. Coelho Lisboa, 500", lat: -23.5421, lng: -46.5712, insta: "mansaosertaneja", genre: "sertanejo", type: "Balada Sertaneja Estilosa", price: "R$ 35 a R$ 75" },
  { name: "Rancho da Costela Lounge", neighborhood: "Santana", address: "R. Dr. Zuquim, 1400", lat: -23.4989, lng: -46.6234, insta: "ranchodacostelasp", genre: "sertanejo", type: "Costela Fogo de Chão & Modão", price: "R$ 35 a R$ 70" },
  { name: "Espaço Hall SP", neighborhood: "Barra Funda", address: "Av. Olavo Fontoura, 1200", lat: -23.5182, lng: -46.6412, insta: "espacohallsp", genre: "funk", type: "Grandes Festas & Festivais", price: "R$ 50 a R$ 130" },
  { name: "Club 33", neighborhood: "Barra Funda", address: "Av. Pompéia, 33", lat: -23.5289, lng: -46.6892, insta: "club33sp", genre: "funk", type: "Funk, Trap & Luz Negra", price: "R$ 35 a R$ 80" },
  { name: "Heavy Baile Club", neighborhood: "Centro Histórico", address: "R. Bento Freitas, 300", lat: -23.5448, lng: -46.6462, insta: "heavybaile", genre: "funk", type: "Passinho & Graves Pesados", price: "R$ 30 a R$ 70" },
  { name: "Baile do Helipa Club", neighborhood: "Ipiranga", address: "Estrada das Lágrimas, 1500", lat: -23.6082, lng: -46.5912, insta: "bailedohelipa", genre: "funk", type: "A Essência do Funk Paulista", price: "R$ 25 a R$ 60" },
  { name: "DZ7 Lounge", neighborhood: "Santo Amaro", address: "Av. Guido Caloi, 1100", lat: -23.6542, lng: -46.7212, insta: "dz7lounge", genre: "funk", type: "Lounge Narguilé & Paredão", price: "R$ 30 a R$ 60" },
  { name: "Caribbean Disco Club", neighborhood: "Pinheiros", address: "R. dos Pinheiros, 1200", lat: -23.5672, lng: -46.6912, insta: "caribbeandiscosp", genre: "funk", type: "Reggaeton, Pop & Funk", price: "R$ 40 a R$ 85" },
  { name: "Blitz Haus", neighborhood: "Consolação", address: "R. Augusta, 657", lat: -23.5518, lng: -46.6519, insta: "blitzhaus", genre: "rock", type: "Games Retrô, Sinuca & Rock", price: "R$ 35 a R$ 75" },
  { name: "Lions Rock Bar", neighborhood: "Pinheiros", address: "R. Teodoro Sampaio, 1800", lat: -23.5612, lng: -46.6882, insta: "lionsrockbar", genre: "rock", type: "Voz & Violão, Chopp & Sinuca", price: "R$ 25 a R$ 50" },
  { name: "Casa de Pedra Bar", neighborhood: "Mooca", address: "R. Juventus, 450", lat: -23.5612, lng: -46.5942, insta: "casadepedramooca", genre: "rock", type: "Rock Acústico na Mooca", price: "R$ 25 a R$ 50" },
  { name: "Lust Club", neighborhood: "Bela Vista", address: "R. Frei Caneca, 1024", lat: -23.5572, lng: -46.6542, insta: "lustclubsp", genre: "eletronica", type: "Balada Eletrônica & Dark Room", price: "R$ 40 a R$ 90" },
  { name: "Igrejinha Bar", neighborhood: "Consolação", address: "R. Fernando de Albuquerque, 302", lat: -23.5528, lng: -46.6552, insta: "barigrejinha", genre: "eletronica", type: "Drinks Autorais & Som Vintage", price: "R$ 30 a R$ 65" },
  { name: "Over Night Club Flash", neighborhood: "Moema", address: "Av. Chibarás, 400", lat: -23.6042, lng: -46.6612, insta: "overnightclub", genre: "eletronica", type: "Pista Retrô & Hits 90", price: "R$ 45 a R$ 90" },
  { name: "The Week SP Memorial", neighborhood: "Lapa", address: "R. Guaicurus, 324", lat: -23.5242, lng: -46.6912, insta: "theweeksp", genre: "eletronica", type: "Mega Pista Eletrônica", price: "R$ 60 a R$ 130" },
  { name: "Carioca Interlagos", neighborhood: "Interlagos", address: "Av. Interlagos, 3000", lat: -23.6789, lng: -46.6954, insta: "cariocaclub", genre: "pagode", type: "Pagode de Domingo & Feijoada", price: "R$ 30 a R$ 65" },
  { name: "Vila JK Sunset", neighborhood: "Vila Olímpia", address: "R. Funchal, 500", lat: -23.5932, lng: -46.6882, insta: "villajk_", genre: "sertanejo", type: "Sunset Party & Sertanejo", price: "R$ 50 a R$ 110" },
  { name: "Piratininga Bar", neighborhood: "Vila Madalena", address: "R. Wisard, 149", lat: -23.5539, lng: -46.6921, insta: "piratiningabar", genre: "pagode", type: "Bossa Nova, Samba & Jazz", price: "R$ 30 a R$ 65" },
  { name: "São Cristóvão Bar", neighborhood: "Vila Madalena", address: "R. Aspicuelta, 533", lat: -23.5545, lng: -46.6914, insta: "saocristovaobar", genre: "pagode", type: "Futebol, Chopp & Choro", price: "R$ 25 a R$ 55" },
  { name: "Mercearia São Pedro", neighborhood: "Vila Madalena", address: "R. Rodésia, 34", lat: -23.5512, lng: -46.6934, insta: "merceariasaopedro", genre: "rock", type: "Boemia Literária & Cerveja", price: "R$ 20 a R$ 45" },
  { name: "Empress Club", neighborhood: "Moema", address: "Al. dos Maracatins, 1000", lat: -23.6078, lng: -46.6621, insta: "empressclubsp", genre: "eletronica", type: "House Melódico & Coquetéis", price: "R$ 50 a R$ 100" },
  { name: "Clash Club Retrô", neighborhood: "Barra Funda", address: "R. Barra Funda, 837", lat: -23.5272, lng: -46.6562, insta: "clashclubsp", genre: "eletronica", type: "Techno & House Clássico", price: "R$ 45 a R$ 90" }
];

// Monta lista completa de 110 baladas reais
REAL_BALADAS_EXTRA.forEach((item, index) => {
  const images = [
    "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1000&q=80",
    "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1000&q=80",
    "https://images.unsplash.com/photo-1545128485-c400e7702796?auto=format&fit=crop&w=1000&q=80",
    "https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?auto=format&fit=crop&w=1000&q=80",
    "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1000&q=80"
  ];
  const img = images[index % images.length];

  BALADAS_110.push({
    id: `balada-${item.insta}-${index + 20}`,
    category: "baladas",
    name: item.name,
    tagline: `${item.type} no coração de ${item.neighborhood}`,
    genre: item.genre as any,
    subType: item.type,
    subTypeEmoji: item.genre === "eletronica" ? "⚡" : item.genre === "sertanejo" ? "🤠" : item.genre === "pagode" ? "🪘" : item.genre === "rock" ? "🎸" : "🔊",
    neighborhood: item.neighborhood,
    address: `${item.address} - ${item.neighborhood}, São Paulo - SP`,
    lat: item.lat,
    lng: item.lng,
    image: img,
    gallery: [img],
    rating: Number((4.5 + ((index % 5) * 0.1)).toFixed(1)),
    reviewsCount: 1200 + (index * 85),
    openToday: true,
    openHours: "Hoje das 21:00 às 05:00",
    isAfterHours: true,
    closesAt: "05:00",
    priceCategory: "medium",
    entryPrice: item.price,
    priceDescription: "Pista climatizada, área VIP e os melhores DJs e atrações de São Paulo",
    hasVipList: true,
    allowsReservation: true,
    hasParking: true,
    whatsapp: `55119${80000000 + index}`,
    instagram: item.insta,
    highlight: `Ambiente exclusivo com o melhor do ${item.genre} e coquetelaria em ${item.neighborhood}.`,
    tags: [item.type, item.neighborhood, "Noite Paulistana", "Música ao Vivo"],
    amenities: ["pista_danca", "drinks", "after_madrugada"]
  });
});
