import { VenueRawItem } from "./data-baladas";

export const MOTEIS_80: VenueRawItem[] = [
  {
    id: "motel-lush",
    category: "moteis",
    name: "Lush Motel",
    tagline: "Design contemporâneo, teto solar retrátil, hidro spa e piscina privativa",
    motelStyle: "piscina",
    subType: "Suíte Spa & Piscina Privativa",
    subTypeEmoji: "🏊‍♂️",
    neighborhood: "Ipiranga",
    address: "Av. do Estado, 6600 - Ipiranga, São Paulo - SP, 04216-000",
    lat: -23.5842,
    lng: -46.6089,
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1000&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1000&q=80"
    ],
    rating: 4.9,
    reviewsCount: 4200,
    openToday: true,
    openHours: "Aberto 24 horas",
    priceCategory: "high",
    entryPrice: "Período 4h a partir de R$ 180",
    priceDescription: "Suítes tecnológicas com automação por tablet, cascata, sauna seca e piscina aquecida",
    hasVipList: false,
    allowsReservation: true,
    hasParking: true,
    hasHydro: true,
    hasPool: true,
    hasPrivateGarage: true,
    periodHours: "Período 4 horas ou Pernoite",
    whatsapp: "551122710020",
    instagram: "lushmotel",
    highlight: "Conceito de hotelaria de luxo com alta gastronomia 24h e teto solar panorâmico.",
    tags: ["Piscina Aquecida", "Teto Solar Retrátil", "Hidromassagem Dupla", "Garagem Privativa", "Automação iPad"],
    amenities: ["drinks"]
  },
  {
    id: "motel-apple",
    category: "moteis",
    name: "Apple Motel",
    tagline: "Design escandinavo, iluminação cromoterápica relaxante e tecnologia touch",
    motelStyle: "design",
    subType: "Design Escandinavo & Hidro",
    subTypeEmoji: "✨",
    neighborhood: "Barra Funda",
    address: "Av. Marquês de São Vicente, 1670 - Barra Funda, São Paulo - SP, 01139-002",
    lat: -23.5189,
    lng: -46.6712,
    image: "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1000&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1000&q=80"
    ],
    rating: 4.8,
    reviewsCount: 3100,
    openToday: true,
    openHours: "Aberto 24 horas",
    priceCategory: "medium",
    entryPrice: "Período 4h a partir de R$ 130",
    priceDescription: "Suítes minimalistas com mármore, ar digital silencioso e chuveiro duplo",
    hasVipList: false,
    allowsReservation: true,
    hasParking: true,
    hasHydro: true,
    hasPool: false,
    hasPrivateGarage: true,
    periodHours: "Período 4 horas ou Pernoite",
    whatsapp: "551136113854",
    instagram: "applemotel",
    highlight: "Visual clean e moderno com hidro espaçosa e excelente gastronomia internacional.",
    tags: ["Design Minimalista", "Hidromassagem", "Chuveiro Duplo", "Cromoterapia"],
    amenities: ["drinks"]
  },
  {
    id: "motel-tout",
    category: "moteis",
    name: "Motel Tout",
    tagline: "Suítes modernas com cascata iluminada, hidro dupla e atendimento discreto",
    motelStyle: "hidro",
    subType: "Hidromassagem & Cascata Iluminada",
    subTypeEmoji: "🛁",
    neighborhood: "Santo Amaro",
    address: "Av. Washington Luís, 1024 - Santo Amaro, São Paulo - SP, 04662-000",
    lat: -23.6412,
    lng: -46.6912,
    image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.7,
    reviewsCount: 2200,
    openToday: true,
    openHours: "Aberto 24 horas",
    priceCategory: "medium",
    entryPrice: "Período 3h a partir de R$ 145",
    priceDescription: "Suíte duplex com lareira ecológica, hidro com cascata e TV Smart 65 polegadas",
    hasVipList: false,
    allowsReservation: true,
    hasParking: true,
    hasHydro: true,
    hasPool: false,
    hasPrivateGarage: true,
    periodHours: "Período 3 horas ou Pernoite",
    whatsapp: "551155239011",
    instagram: "tout.motel",
    highlight: "Cascata com iluminação suave em leds e som bluetooth integrado à suíte.",
    tags: ["Hidromassagem com Cascata", "Lareira Ecológica", "Garagem com Portão Rápido"],
    amenities: ["drinks"]
  },
  {
    id: "motel-acropoles",
    category: "moteis",
    name: "Motel Acrópoles",
    tagline: "Ampla suíte presidencial com piscina, hidromassagem e sauna a vapor",
    motelStyle: "piscina",
    subType: "Suíte Presidencial & Piscina",
    subTypeEmoji: "🏊‍♂️",
    neighborhood: "Vila Prudente",
    address: "Av. Professor Luiz Ignácio Anhaia Mello, 1800 - Vila Prudente, São Paulo - SP, 03154-000",
    lat: -23.5812,
    lng: -46.5789,
    image: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.7,
    reviewsCount: 3400,
    openToday: true,
    openHours: "Aberto 24 horas",
    priceCategory: "high",
    entryPrice: "Período 4h a partir de R$ 160",
    priceDescription: "Piscina aquecida privativa, teto que abre, sauna e churrasqueira",
    hasVipList: false,
    allowsReservation: true,
    hasParking: true,
    hasHydro: true,
    hasPool: true,
    hasPrivateGarage: true,
    periodHours: "Período 4 horas ou Pernoite",
    whatsapp: "551121546700",
    instagram: "",
    highlight: "Conforto total na Zona Leste com suítes de até 250m² e piscina privativa.",
    tags: ["Piscina Aquecida", "Sauna a Vapor", "Garagem Dupla", "Teto Solar"],
    amenities: ["drinks"]
  },
  {
    id: "motel-harmony",
    category: "moteis",
    name: "Motel Harmony",
    tagline: "Suítes modernas e refinadas a poucos minutos da Faria Lima e Rebouças",
    motelStyle: "hidro",
    subType: "Suítes Executivas & Hidro Dupla",
    subTypeEmoji: "🛁",
    neighborhood: "Pinheiros",
    address: "R. Amália de Noronha, 290 - Pinheiros, São Paulo - SP, 05410-010",
    lat: -23.5542,
    lng: -46.6812,
    image: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.6,
    reviewsCount: 1950,
    openToday: true,
    openHours: "Aberto 24 horas",
    priceCategory: "medium",
    entryPrice: "Período 3h a partir de R$ 115",
    priceDescription: "Localização estratégica perto da Faria Lima com hidromassagem e serviço de quarto",
    hasVipList: false,
    allowsReservation: true,
    hasParking: true,
    hasHydro: true,
    hasPool: false,
    hasPrivateGarage: true,
    periodHours: "Período 3 horas ou Pernoite",
    whatsapp: "551130811234",
    instagram: "motel_harmony",
    highlight: "Praticidade máxima em Pinheiros com higienização hospitalar impecável.",
    tags: ["Pinheiros", "Faria Lima", "Hidromassagem Dupla", "Discrição Absoluta"],
    amenities: ["drinks"]
  },
  {
    id: "motel-zapt",
    category: "moteis",
    name: "Motel Zapt",
    tagline: "Melhor custo-benefício com hidromassagem, ar split silencioso e garagem privativa",
    motelStyle: "economica",
    subType: "Suíte Econômica & Hidro Conforto",
    subTypeEmoji: "🏷️",
    neighborhood: "Mooca",
    address: "Av. Alcântara Machado, 2100 - Mooca, São Paulo - SP, 03102-002",
    lat: -23.5512,
    lng: -46.5982,
    image: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.5,
    reviewsCount: 2800,
    openToday: true,
    openHours: "Aberto 24 horas",
    priceCategory: "low",
    entryPrice: "Período 3h a partir de R$ 99",
    priceDescription: "Suítes aconchegantes com cama king size, hidro e cardápio de petiscos rápidos",
    hasVipList: false,
    allowsReservation: true,
    hasParking: true,
    hasHydro: true,
    hasPool: false,
    hasPrivateGarage: true,
    periodHours: "Período 3 horas ou Pernoite",
    whatsapp: "551126941212",
    instagram: "",
    highlight: "Preço super acessível com conforto garantido e fácil acesso pela Radial Leste.",
    tags: ["Mais Barato", "Radial Leste", "Garagem Fechada", "Ar Condicionado"],
    amenities: ["drinks"]
  },
  {
    id: "motel-swing",
    category: "moteis",
    name: "Swing Motel",
    tagline: "Ícone do luxo no Morumbi com piscinas aquecidas, toboágua e suítes temáticas",
    motelStyle: "piscina",
    subType: "Super Luxo & Piscina com Cascata",
    subTypeEmoji: "🏊‍♂️",
    neighborhood: "Morumbi",
    address: "Av. Morumbi, 6200 - Morumbi, São Paulo - SP, 05650-002",
    lat: -23.6121,
    lng: -46.7142,
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.9,
    reviewsCount: 5100,
    openToday: true,
    openHours: "Aberto 24 horas",
    priceCategory: "high",
    entryPrice: "Período 4h a partir de R$ 195",
    priceDescription: "Piscina privativa aquecida com teto solar, cascata e pista de dança com pole dance",
    hasVipList: false,
    allowsReservation: true,
    hasParking: true,
    hasHydro: true,
    hasPool: true,
    hasPrivateGarage: true,
    periodHours: "Período 4 horas ou Pernoite",
    whatsapp: "551137428800",
    instagram: "swingmotelsp",
    highlight: "Pioneiro absoluto em sofisticação com suítes tríplex e alta gastronomia internacional.",
    tags: ["Piscina Aquecida", "Morumbi Nobre", "Pole Dance", "Teto Retrátil"],
    amenities: ["drinks"]
  }
];

const MOTEIS_EXTRA = [
  { name: "Motel Belle", neighborhood: "Butantã", address: "Av. Marginal do Rio Pinheiros, 1100", lat: -23.5712, lng: -46.7112, insta: "bellemotel", style: "design", price: "Período 4h a partir de R$ 150", pool: false, hydro: true },
  { name: "Motel Lumini", neighborhood: "Santana", address: "Av. Santos Dumont, 2200", lat: -23.5042, lng: -46.6289, insta: "", style: "hidro", price: "Período 4h a partir de R$ 140", pool: false, hydro: true },
  { name: "Motel Point", neighborhood: "Tatuapé", address: "R. Serra de Bragança, 1400", lat: -23.5412, lng: -46.5612, insta: "pointmotelabc", style: "tematica", price: "Período 3h a partir de R$ 110", pool: false, hydro: true },
  { name: "Motel Censurado", neighborhood: "Casa Verde", address: "Av. Engenheiro Caetano Álvares, 2100", lat: -23.5089, lng: -46.6542, insta: "", style: "tematica", price: "Período 3h a partir de R$ 105", pool: false, hydro: true },
  { name: "Motel Caribe", neighborhood: "Barra Funda", address: "R. Sérgio Tomás, 450", lat: -23.5212, lng: -46.6492, insta: "motel_caribe", style: "piscina", price: "Período 4h a partir de R$ 170", pool: true, hydro: true },
  { name: "Motel Alvorada", neighborhood: "Moema", address: "Av. Ibirapuera, 1800", lat: -23.6012, lng: -46.6598, insta: "", style: "design", price: "Período 4h a partir de R$ 155", pool: false, hydro: true },
  { name: "Motel Riunione", neighborhood: "Penha", address: "Av. Gabriela Mistral, 850", lat: -23.5189, lng: -46.5382, insta: "", style: "hidro", price: "Período 3h a partir de R$ 115", pool: false, hydro: true },
  { name: "Motel Prime", neighborhood: "Santana", address: "R. Dr. Zuquim, 1800", lat: -23.4982, lng: -46.6212, insta: "", style: "design", price: "Período 4h a partir de R$ 145", pool: false, hydro: true },
  { name: "Motel Opium", neighborhood: "Vila Mariana", address: "R. Vergueiro, 2900", lat: -23.5852, lng: -46.6382, insta: "opium.motel", style: "hidro", price: "Período 3h a partir de R$ 125", pool: false, hydro: true },
  { name: "Motel Virtual", neighborhood: "Interlagos", address: "Av. Interlagos, 4200", lat: -23.6892, lng: -46.6982, insta: "", style: "design", price: "Período 4h a partir de R$ 135", pool: true, hydro: true },
  { name: "Motel Replay", neighborhood: "Mooca", address: "R. Borges de Figueiredo, 1400", lat: -23.5562, lng: -46.6012, insta: "", style: "economica", price: "Período 3h a partir de R$ 95", pool: false, hydro: true },
  { name: "Motel Drops São Paulo", neighborhood: "Santana", address: "Av. Braz Leme, 2800", lat: -23.5012, lng: -46.6489, insta: "dropsmotel", style: "design", price: "Período 4h a partir de R$ 160", pool: true, hydro: true },
  { name: "Motel Vitrine", neighborhood: "Aricanduva", address: "Av. Aricanduva, 4500", lat: -23.5689, lng: -46.5182, insta: "", style: "tematica", price: "Período 3h a partir de R$ 100", pool: false, hydro: true },
  { name: "Motel Colonial", neighborhood: "Santo Amaro", address: "Av. João Dias, 2400", lat: -23.6489, lng: -46.7189, insta: "", style: "economica", price: "Período 3h a partir de R$ 90", pool: false, hydro: true },
  { name: "Motel Riviera", neighborhood: "Vila Leopoldina", address: "Av. Dr. Gastão Vidigal, 1500", lat: -23.5312, lng: -46.7289, insta: "", style: "hidro", price: "Período 4h a partir de R$ 130", pool: false, hydro: true },
  { name: "Motel Côncavo e Convexo", neighborhood: "Butantã", address: "Av. Corifeu de Azevedo Marques, 2100", lat: -23.5742, lng: -46.7282, insta: "", style: "design", price: "Período 4h a partir de R$ 145", pool: false, hydro: true },
  { name: "Motel Farao's", neighborhood: "Barra Funda", address: "Av. Otaviano Alves de Lima, 3200", lat: -23.5112, lng: -46.6812, insta: "", style: "tematica", price: "Período 3h a partir de R$ 120", pool: true, hydro: true },
  { name: "Motel Status", neighborhood: "Ipiranga", address: "R. Vergueiro, 7800", lat: -23.6089, lng: -46.6112, insta: "", style: "hidro", price: "Período 3h a partir de R$ 110", pool: false, hydro: true },
  { name: "Motel Fantasy", neighborhood: "Barra Funda", address: "R. Achilles Orlando, 100", lat: -23.5212, lng: -46.6621, insta: "", style: "tematica", price: "Período 3h a partir de R$ 115", pool: false, hydro: true },
  { name: "Motel Le Nid", neighborhood: "Morumbi", address: "Av. Francisco Morato, 4100", lat: -23.5982, lng: -46.7212, insta: "", style: "design", price: "Período 4h a partir de R$ 165", pool: true, hydro: true },
  { name: "Motel Forest Hills", neighborhood: "Morumbi", address: "R. Dom Armando Lombard, 800", lat: -23.6042, lng: -46.7182, insta: "", style: "piscina", price: "Período 4h a partir de R$ 180", pool: true, hydro: true },
  { name: "Motel Vyss", neighborhood: "Jabaquara", address: "Av. George Corbisier, 900", lat: -23.6412, lng: -46.6482, insta: "", style: "design", price: "Período 3h a partir de R$ 120", pool: false, hydro: true },
  { name: "Motel Emoções", neighborhood: "São Miguel", address: "Av. São Miguel, 3500", lat: -23.4982, lng: -46.4682, insta: "", style: "economica", price: "Período 3h a partir de R$ 85", pool: false, hydro: true },
  { name: "Motel Confidence", neighborhood: "Itaquera", address: "Av. Jacu-Pêssego, 1200", lat: -23.5312, lng: -46.4482, insta: "", style: "hidro", price: "Período 3h a partir de R$ 95", pool: false, hydro: true },
  { name: "Motel Dallas", neighborhood: "Santana", address: "Av. Educador Paulo Freire, 1100", lat: -23.5042, lng: -46.5782, insta: "", style: "hidro", price: "Período 3h a partir de R$ 110", pool: false, hydro: true },
  { name: "Motel Caribbean", neighborhood: "São Mateus", address: "Av. Ragueb Chohfi, 2100", lat: -23.6012, lng: -46.4682, insta: "", style: "tematica", price: "Período 3h a partir de R$ 90", pool: false, hydro: true },
  { name: "Motel Casablanca", neighborhood: "Pirituba", address: "Av. Raimundo Pereira de Magalhães, 4500", lat: -23.4882, lng: -46.7212, insta: "", style: "economica", price: "Período 3h a partir de R$ 85", pool: false, hydro: true },
  { name: "Motel Platinum", neighborhood: "Santo Amaro", address: "Av. Nações Unidas, 18500", lat: -23.6712, lng: -46.7212, insta: "", style: "design", price: "Período 4h a partir de R$ 150", pool: true, hydro: true },
  { name: "Motel Atenas", neighborhood: "Vila Guilherme", address: "R. Joaquina Ramalho, 800", lat: -23.5112, lng: -46.6112, insta: "", style: "hidro", price: "Período 3h a partir de R$ 105", pool: false, hydro: true },
  { name: "Motel Kamasutra", neighborhood: "Santana", address: "Av. General Ataliba Leonel, 2500", lat: -23.4912, lng: -46.6112, insta: "", style: "tematica", price: "Período 3h a partir de R$ 115", pool: false, hydro: true },
  { name: "Motel Medieval", neighborhood: "Tatuapé", address: "R. Apucarana, 1200", lat: -23.5412, lng: -46.5682, insta: "", style: "tematica", price: "Período 3h a partir de R$ 110", pool: false, hydro: true },
  { name: "Motel Nexus", neighborhood: "Vila Maria", address: "Av. Guilherme Cotching, 1400", lat: -23.5182, lng: -46.5912, insta: "", style: "design", price: "Período 3h a partir de R$ 120", pool: false, hydro: true },
  { name: "Motel Passion", neighborhood: "Pinheiros", address: "R. Henrique Schaumann, 400", lat: -23.5582, lng: -46.6812, insta: "", style: "hidro", price: "Período 3h a partir de R$ 130", pool: false, hydro: true },
  { name: "Motel Royale", neighborhood: "Morumbi", address: "Av. Padre Lebret, 800", lat: -23.6012, lng: -46.7112, insta: "", style: "design", price: "Período 4h a partir de R$ 170", pool: true, hydro: true },
  { name: "Motel Sagitarius", neighborhood: "Mooca", address: "Av. Paes de Barros, 2400", lat: -23.5682, lng: -46.5912, insta: "", style: "hidro", price: "Período 3h a partir de R$ 115", pool: false, hydro: true },
  { name: "Motel Secrets", neighborhood: "Butantã", address: "Av. Vital Brasil, 850", lat: -23.5712, lng: -46.7082, insta: "", style: "design", price: "Período 3h a partir de R$ 125", pool: false, hydro: true },
  { name: "Motel Studio A", neighborhood: "Lapa", address: "R. Clélia, 1800", lat: -23.5282, lng: -46.6912, insta: "", style: "hidro", price: "Período 3h a partir de R$ 110", pool: false, hydro: true },
  { name: "Motel Supreme", neighborhood: "Vila Prudente", address: "Av. Zelina, 1100", lat: -23.5882, lng: -46.5782, insta: "", style: "piscina", price: "Período 4h a partir de R$ 160", pool: true, hydro: true },
  { name: "Motel Tangará", neighborhood: "Interlagos", address: "Av. Senador Teotônio Vilela, 2800", lat: -23.6982, lng: -46.7082, insta: "", style: "economica", price: "Período 3h a partir de R$ 85", pool: false, hydro: true },
  { name: "Motel The Best", neighborhood: "Pinheiros", address: "Av. das Nações Unidas, 10500", lat: -23.5912, lng: -46.6982, insta: "", style: "design", price: "Período 4h a partir de R$ 155", pool: true, hydro: true },
  { name: "Motel Tramps", neighborhood: "Barra Funda", address: "R. Quirino dos Santos, 150", lat: -23.5242, lng: -46.6612, insta: "", style: "hidro", price: "Período 3h a partir de R$ 115", pool: false, hydro: true },
  { name: "Motel Vogue", neighborhood: "Tatuapé", address: "R. Emília Marengo, 900", lat: -23.5482, lng: -46.5642, insta: "", style: "design", price: "Período 3h a partir de R$ 130", pool: false, hydro: true },
  { name: "Motel Xanadu", neighborhood: "Ipiranga", address: "R. Bom Pastor, 2100", lat: -23.5982, lng: -46.6042, insta: "", style: "hidro", price: "Período 3h a partir de R$ 110", pool: false, hydro: true },
  { name: "Motel Zeus", neighborhood: "Vila Guilherme", address: "R. Maria Cândida, 1400", lat: -23.5082, lng: -46.6142, insta: "", style: "tematica", price: "Período 3h a partir de R$ 120", pool: false, hydro: true },
  { name: "Motel Black & White", neighborhood: "Tatuapé", address: "Av. Salim Farah Maluf, 3100", lat: -23.5512, lng: -46.5742, insta: "", style: "design", price: "Período 3h a partir de R$ 125", pool: false, hydro: true },
  { name: "Motel Champagne", neighborhood: "Jabaquara", address: "Av. Jabaquara, 2400", lat: -23.6212, lng: -46.6412, insta: "", style: "hidro", price: "Período 3h a partir de R$ 115", pool: false, hydro: true },
  { name: "Motel Diamante", neighborhood: "Santana", address: "Av. Cruzeiro do Sul, 3100", lat: -23.5012, lng: -46.6242, insta: "", style: "hidro", price: "Período 3h a partir de R$ 110", pool: false, hydro: true },
  { name: "Motel Eclipse", neighborhood: "Vila Leopoldina", address: "Av. Imperatriz Leopoldina, 800", lat: -23.5282, lng: -46.7242, insta: "", style: "design", price: "Período 4h a partir de R$ 140", pool: false, hydro: true },
  { name: "Motel Flash", neighborhood: "Casa Verde", address: "R. Relíquia, 450", lat: -23.5112, lng: -46.6612, insta: "", style: "economica", price: "Período 3h a partir de R$ 90", pool: false, hydro: true },
  { name: "Motel Glamour", neighborhood: "Santo Amaro", address: "Av. Santo Amaro, 4200", lat: -23.6312, lng: -46.6912, insta: "", style: "design", price: "Período 3h a partir de R$ 135", pool: false, hydro: true },
  { name: "Motel Hollywood", neighborhood: "Interlagos", address: "Av. Rio Bonito, 1400", lat: -23.6912, lng: -46.7012, insta: "", style: "tematica", price: "Período 3h a partir de R$ 110", pool: false, hydro: true },
  { name: "Motel Ibiza", neighborhood: "Barra Funda", address: "R. Norma Pieruccini Giannotti, 400", lat: -23.5212, lng: -46.6542, insta: "", style: "piscina", price: "Período 4h a partir de R$ 165", pool: true, hydro: true },
  { name: "Motel Kiss", neighborhood: "Penha", address: "Av. Condessa Elizabeth de Robiano, 4800", lat: -23.5182, lng: -46.5512, insta: "", style: "economica", price: "Período 3h a partir de R$ 85", pool: false, hydro: true },
  { name: "Motel Libid's", neighborhood: "Mooca", address: "R. da Mooca, 3800", lat: -23.5582, lng: -46.5882, insta: "", style: "hidro", price: "Período 3h a partir de R$ 105", pool: false, hydro: true },
  { name: "Motel Magic", neighborhood: "Freguesia do Ó", address: "Av. Inajar de Souza, 1800", lat: -23.4982, lng: -46.6812, insta: "", style: "tematica", price: "Período 3h a partir de R$ 95", pool: false, hydro: true },
  { name: "Motel New Star", neighborhood: "Santana", address: "Av. Leôncio de Magalhães, 1100", lat: -23.4912, lng: -46.6212, insta: "", style: "hidro", price: "Período 3h a partir de R$ 115", pool: false, hydro: true },
  { name: "Motel Oasis", neighborhood: "Ipiranga", address: "Av. Nazaré, 1900", lat: -23.5942, lng: -46.6082, insta: "", style: "piscina", price: "Período 4h a partir de R$ 155", pool: true, hydro: true },
  { name: "Motel Paris", neighborhood: "Jabaquara", address: "Av. Engenheiro Armando de Arruda Pereira, 1600", lat: -23.6442, lng: -46.6442, insta: "", style: "design", price: "Período 3h a partir de R$ 125", pool: false, hydro: true },
  { name: "Motel Quatro Estações", neighborhood: "Tatuapé", address: "R. Tuiuti, 2200", lat: -23.5382, lng: -46.5712, insta: "", style: "hidro", price: "Período 3h a partir de R$ 110", pool: false, hydro: true },
  { name: "Motel Romance", neighborhood: "Tatuapé", address: "R. Serra de Botucatu, 1100", lat: -23.5412, lng: -46.5642, insta: "", style: "hidro", price: "Período 3h a partir de R$ 105", pool: false, hydro: true },
  { name: "Motel Seduction", neighborhood: "Santo Amaro", address: "Av. Adolfo Pinheiro, 1500", lat: -23.6512, lng: -46.7082, insta: "", style: "design", price: "Período 3h a partir de R$ 130", pool: false, hydro: true },
  { name: "Motel Tantra", neighborhood: "Pinheiros", address: "R. Mourato Coelho, 700", lat: -23.5582, lng: -46.6882, insta: "", style: "tematica", price: "Período 3h a partir de R$ 140", pool: false, hydro: true },
  { name: "Motel Unique", neighborhood: "Barra Funda", address: "Av. Presidente Castelo Branco, 4900", lat: -23.5182, lng: -46.6682, insta: "", style: "piscina", price: "Período 4h a partir de R$ 175", pool: true, hydro: true },
  { name: "Motel Venus", neighborhood: "Morumbi", address: "R. Senador Otávio Mangabeira, 300", lat: -23.6082, lng: -46.7142, insta: "", style: "design", price: "Período 4h a partir de R$ 160", pool: false, hydro: true },
  { name: "Motel Wind", neighborhood: "Santana", address: "R. Voluntários da Pátria, 3500", lat: -23.4912, lng: -46.6282, insta: "", style: "hidro", price: "Período 3h a partir de R$ 115", pool: false, hydro: true },
  { name: "Motel Xodó", neighborhood: "Mooca", address: "Av. Cassandoca, 600", lat: -23.5512, lng: -46.5912, insta: "", style: "economica", price: "Período 3h a partir de R$ 90", pool: false, hydro: true },
  { name: "Motel Yes", neighborhood: "Interlagos", address: "Av. Robert Kennedy, 2400", lat: -23.6912, lng: -46.7112, insta: "", style: "design", price: "Período 3h a partir de R$ 120", pool: false, hydro: true },
  { name: "Motel Zen", neighborhood: "Jardins", address: "R. Pamplona, 1200", lat: -23.5642, lng: -46.6582, insta: "", style: "design", price: "Período 4h a partir de R$ 180", pool: true, hydro: true },
  { name: "Motel Millenium", neighborhood: "Santana", address: "Av. Nova Cantareira, 1800", lat: -23.4882, lng: -46.6182, insta: "", style: "hidro", price: "Período 3h a partir de R$ 115", pool: false, hydro: true },
  { name: "Motel Sublime", neighborhood: "Tatuapé", address: "R. Monte Serrat, 850", lat: -23.5412, lng: -46.5612, insta: "", style: "piscina", price: "Período 4h a partir de R$ 165", pool: true, hydro: true },
  { name: "Motel Alpha", neighborhood: "Barra Funda", address: "Av. Francisco Matarazzo, 1400", lat: -23.5282, lng: -46.6782, insta: "", style: "design", price: "Período 4h a partir de R$ 150", pool: false, hydro: true },
  { name: "Motel Caravellas", neighborhood: "Ipiranga", address: "Av. Dom Pedro I, 900", lat: -23.5782, lng: -46.6112, insta: "", style: "hidro", price: "Período 3h a partir de R$ 105", pool: false, hydro: true },
  { name: "Motel Dallas Sul", neighborhood: "Santo Amaro", address: "Av. das Nações Unidas, 14000", lat: -23.6282, lng: -46.7012, insta: "", style: "piscina", price: "Período 4h a partir de R$ 160", pool: true, hydro: true }
];

MOTEIS_EXTRA.forEach((item, index) => {
  const images = [
    "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1000&q=80",
    "https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1000&q=80",
    "https://images.unsplash.com/photo-1590490360182-c33d57733427?auto=format&fit=crop&w=1000&q=80",
    "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1000&q=80",
    "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1000&q=80"
  ];
  const img = images[index % images.length];

  MOTEIS_80.push({
    id: `motel-extra-${index + 10}`,
    category: "moteis",
    name: item.name,
    tagline: `Suítes confortáveis com hidromassagem e privacidade em ${item.neighborhood}`,
    motelStyle: item.style as any,
    subType: item.style === "piscina" ? "Piscina Privativa & Hidro" : item.style === "design" ? "Design Contemporâneo" : item.style === "tematica" ? "Suíte Temática Especial" : item.style === "economica" ? "Suíte Econômica com Conforto" : "Hidromassagem com Cromoterapia",
    subTypeEmoji: item.style === "piscina" ? "🏊‍♂️" : item.style === "design" ? "✨" : item.style === "tematica" ? "🎭" : item.style === "economica" ? "🏷️" : "🛁",
    neighborhood: item.neighborhood,
    address: `${item.address} - ${item.neighborhood}, São Paulo - SP`,
    lat: item.lat,
    lng: item.lng,
    image: img,
    gallery: [img],
    rating: Number((4.5 + ((index % 4) * 0.1)).toFixed(1)),
    reviewsCount: 1100 + (index * 60),
    openToday: true,
    openHours: "Aberto 24 horas",
    priceCategory: "medium",
    entryPrice: item.price,
    priceDescription: "Higienização esterilizada, ar-condicionado quente/frio, TV Smart e garagem privativa",
    hasVipList: false,
    allowsReservation: true,
    hasParking: true,
    hasHydro: item.hydro,
    hasPool: item.pool,
    hasPrivateGarage: true,
    periodHours: "Período 3h a 4h ou Pernoite",
    whatsapp: `55119${60000000 + index}`,
    instagram: item.insta,
    highlight: `Excelente opção de motel em ${item.neighborhood} com discrição absoluta e conforto.`,
    tags: ["Garagem Privativa", "Aberto 24 Horas", "Ar Split", item.neighborhood],
    amenities: ["drinks"]
  });
});
