import { VenueRawItem } from "./data-baladas";

export const RESTAURANTES_110: VenueRawItem[] = [
  {
    id: "rest-coco-bambu-analia",
    category: "restaurantes",
    name: "Coco Bambu Anália Franco",
    tagline: "Frutos do mar fartos, brinquedão gigante com monitores e adega sofisticada",
    cuisine: "kids",
    subType: "Frutos do Mar & Espaço Kids Gigante",
    subTypeEmoji: "🧸",
    neighborhood: "Tatuapé",
    address: "R. Azevedo Soares, 2150 - Jardim Anália Franco, São Paulo - SP, 03322-002",
    lat: -23.5512,
    lng: -46.5621,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80"
    ],
    rating: 4.8,
    reviewsCount: 16500,
    openToday: true,
    openHours: "Hoje das 11:30 às 23:30",
    priceCategory: "high",
    entryPrice: "Pratos a partir de R$ 99 (serve 3 pessoas)",
    priceDescription: "Porções generosas para a família, brinquedão com circuito e monitores treinados",
    hasVipList: false,
    allowsReservation: true,
    hasKidsSpace: true,
    hasParking: true,
    whatsapp: "551143803620",
    instagram: "cocobambuoficial",
    highlight: "Espaço Kids Play com escorregadores tubulares, labirinto, jogos e monitoria dedicada.",
    tags: ["Espaço Kids Gigante", "Frutos do Mar", "Camarão Internacional", "Estacionamento com Valet", "Adega Climatizada"],
    menuHighlights: ["Camarão Coco Bambu", "Camarão Internacional", "Moqueca Cearense de Frutos do Mar", "Torta de Limão"],
    amenities: ["petiscos", "chopp", "drinks"]
  },
  {
    id: "rest-manihi-sushi-perdizes",
    category: "restaurantes",
    name: "Manihi Sushi Perdizes",
    tagline: "Rodízio japonês premium premiado com brinquedão infantil e recreação",
    cuisine: "kids",
    subType: "Rodízio Japonês com Espaço Kids",
    subTypeEmoji: "🧸",
    neighborhood: "Perdizes",
    address: "R. Apinajés, 1359 - Perdizes, São Paulo - SP, 05017-000",
    lat: -23.5412,
    lng: -46.6821,
    image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1000&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1000&q=80",
      "https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=1000&q=80"
    ],
    rating: 4.8,
    reviewsCount: 7800,
    openToday: true,
    openHours: "Hoje das 12:00 às 23:00",
    priceCategory: "high",
    entryPrice: "Rodízio Gourmet R$ 149 por pessoa",
    priceDescription: "Sushis trufados, camarões empanados e área kids envidraçada para os pais visualizarem",
    hasVipList: false,
    allowsReservation: true,
    hasKidsSpace: true,
    hasParking: true,
    whatsapp: "551136720230",
    instagram: "manihisushi",
    highlight: "Um dos melhores rodízios japoneses da capital com espaço kids completo e monitoras.",
    tags: ["Espaço Kids com Monitor", "Sushis Trufados", "Polvo na Brasa", "Perdizes", "Rodízio Premiado"],
    menuHighlights: ["Niguiri de Salmão com Foie Gras", "Uramaki Ebi Especial", "Carpaccio de Polvo Trufado", "Petit Gâteau"],
    amenities: ["petiscos", "drinks"]
  },
  {
    id: "rest-praca-sao-lourenco",
    category: "restaurantes",
    name: "Praça São Lourenço",
    tagline: "Oásis verde na Vila Olímpia com lago de carpas, forno a lenha e monitores infantis",
    cuisine: "kids",
    subType: "Cozinha Comfort & Bosque Kids",
    subTypeEmoji: "🧸",
    neighborhood: "Vila Olímpia",
    address: "R. Casa do Ator, 608 - Vila Olímpia, São Paulo - SP, 04546-002",
    lat: -23.5978,
    lng: -46.6812,
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=80"
    ],
    rating: 4.8,
    reviewsCount: 6400,
    openToday: true,
    openHours: "Hoje das 12:00 às 23:00",
    priceCategory: "high",
    entryPrice: "Buffet ou à la carte a partir de R$ 130",
    priceDescription: "Jardim arborizado de 2.000m², casa na árvore e atividades ecológicas para crianças",
    hasVipList: false,
    allowsReservation: true,
    hasKidsSpace: true,
    hasParking: true,
    whatsapp: "551130539300",
    instagram: "pracasaolourenco",
    highlight: "Casa na árvore e recreacionistas infantis em meio à natureza no coração da Vila Olímpia.",
    tags: ["Área Verde Kids", "Casa na Árvore", "Lago de Carpas", "Forno a Lenha", "Almoço em Família"],
    amenities: ["petiscos", "chopp", "drinks"]
  },
  {
    id: "rest-chacara-santa-cecilia",
    category: "restaurantes",
    name: "Chácara Santa Cecília",
    tagline: "Bosque preservado com lago, horta orgânica e ampla área de recreação infantil",
    cuisine: "kids",
    subType: "Gastronomia da Terra & Espaço Kids",
    subTypeEmoji: "🧸",
    neighborhood: "Pinheiros",
    address: "R. Ferreira de Araújo, 428 - Pinheiros, São Paulo - SP, 05428-000",
    lat: -23.5612,
    lng: -46.6998,
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.7,
    reviewsCount: 5100,
    openToday: true,
    openHours: "Hoje das 12:00 às 23:00",
    priceCategory: "high",
    entryPrice: "Pratos a partir de R$ 85",
    priceDescription: "Espaço kids com oficinas infantis, árvores centenárias e comida brasileira",
    hasVipList: false,
    allowsReservation: true,
    hasKidsSpace: true,
    hasParking: true,
    whatsapp: "551130345000",
    instagram: "chacarasantacecilia",
    highlight: "Ambiente campestre em Pinheiros ideal para almoços familiares tranquilos com crianças.",
    tags: ["Espaço Kids com Recreação", "Bosque Natural", "Pratos Brasileiros", "Pinheiros Família"],
    amenities: ["chopp", "petiscos", "drinks"]
  },
  {
    id: "rest-fogo-de-chao-jardins",
    category: "restaurantes",
    name: "Fogo de Chão Jardins",
    tagline: "A grife máxima do churrasco gaúcho: cortes nobres na brasa e buffet de saladas de luxo",
    cuisine: "churrascaria",
    subType: "Churrascaria Gaúcha de Luxo",
    subTypeEmoji: "🥩",
    neighborhood: "Jardins",
    address: "R. Augusta, 2077 - Cerqueira César, São Paulo - SP, 01413-000",
    lat: -23.5601,
    lng: -46.6632,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.9,
    reviewsCount: 9400,
    openToday: true,
    openHours: "Hoje das 12:00 às 23:30",
    priceCategory: "high",
    entryPrice: "Rodízio Completo R$ 215 por pessoa",
    priceDescription: "Picanha, costela de ripa 12 horas, cordeiro nobre, wagyu e mesa gourmet",
    hasVipList: false,
    allowsReservation: true,
    hasParking: true,
    whatsapp: "551130622226",
    instagram: "fogodechaobr",
    highlight: "Mais de 40 anos de excelência com serviço impecável de passadores e cortes nobres.",
    tags: ["Cortes Nobres", "Picanha Fatiada", "Costela Fogo de Chão", "Jardins", "Carta de Vinhos"],
    amenities: ["petiscos", "drinks", "chopp"]
  },
  {
    id: "rest-vento-haragano",
    category: "restaurantes",
    name: "Vento Haragano",
    tagline: "Tradição do autêntico churrasco gaúcho com adega monumental e cortes nobres",
    cuisine: "churrascaria",
    subType: "Rodízio Tradicional de Carnes Nobres",
    subTypeEmoji: "🥩",
    neighborhood: "Jardins",
    address: "Av. Rebouças, 1001 - Jardins, São Paulo - SP, 05401-150",
    lat: -23.5628,
    lng: -46.6728,
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.8,
    reviewsCount: 8200,
    openToday: true,
    openHours: "Hoje das 12:00 às 23:30",
    priceCategory: "high",
    entryPrice: "Rodízio Nobre R$ 198 por pessoa",
    priceDescription: "Bife de ancho, paleta de cordeiro, leitão à pururuca e buffet mediterrâneo",
    hasVipList: false,
    allowsReservation: true,
    hasParking: true,
    whatsapp: "551130834386",
    instagram: "ventoharagano_oficial",
    highlight: "Adega climatizada para 8.000 garrafas e piano ao vivo no salão principal.",
    tags: ["Cortes de Cordeiro", "Adega Climatizada", "Churrasco Gaúcho", "Piano ao Vivo"],
    amenities: ["petiscos", "chopp", "drinks"]
  },
  {
    id: "rest-fazenda-churrascada",
    category: "restaurantes",
    name: "Fazenda Churrascada",
    tagline: "Parque gastronômico temático com carnes defumadas e espaço kids gigante ao ar livre",
    cuisine: "kids",
    subType: "Churrasco Defumado & Parque Kids",
    subTypeEmoji: "🧸",
    neighborhood: "Morumbi",
    address: "Av. Morumbi, 5594 - Morumbi, São Paulo - SP, 05650-001",
    lat: -23.6082,
    lng: -46.7112,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.8,
    reviewsCount: 11200,
    openToday: true,
    openHours: "Hoje das 12:00 às 23:00",
    priceCategory: "high",
    entryPrice: "Pratos e cortes a partir de R$ 90",
    priceDescription: "Pits de defumação, cortes Tomahawk, brisket texano e tirolesa infantil",
    hasVipList: false,
    allowsReservation: true,
    hasKidsSpace: true,
    hasParking: true,
    whatsapp: "5511999998811",
    instagram: "fazendachurrascada",
    highlight: "Mega estrutura ao ar livre com brinquedão, tirolesa e carne defumada de padrão internacional.",
    tags: ["Espaço Kids com Tirolesa", "Brisket Texano", "Ambiente Fazenda", "Morumbi", "Pet Friendly"],
    amenities: ["petiscos", "chopp", "drinks"]
  },
  {
    id: "rest-terraco-italia",
    category: "restaurantes",
    name: "Terraço Itália",
    tagline: "O topo de São Paulo no 41º andar: culinária italiana refinada e vista panorâmica lendária",
    cuisine: "italiano",
    subType: "Alta Gastronomia Italiana Panorâmica",
    subTypeEmoji: "🍝",
    neighborhood: "Centro Histórico",
    address: "Av. Ipiranga, 344 - 41º e 42º andares - República, São Paulo - SP, 01046-010",
    lat: -23.5469,
    lng: -46.6439,
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.9,
    reviewsCount: 14800,
    openToday: true,
    openHours: "Hoje das 12:00 às 00:00",
    priceCategory: "high",
    entryPrice: "Menu degustação ou à la carte a partir de R$ 180",
    priceDescription: "Pianista ao vivo, velas nas mesas e a vista 360° mais famosa da América do Sul",
    hasVipList: false,
    allowsReservation: true,
    hasParking: true,
    whatsapp: "551121892929",
    instagram: "terracoitalia",
    highlight: "O cenário mais romântico de São Paulo para datas especiais e pedidos de casamento.",
    tags: ["Vista 360 Panorâmica", "Jantar Romântico", "Pianista ao Vivo", "Alta Gastronomia Italiana", "Centro Histórico"],
    amenities: ["musica_ao_vivo", "drinks"]
  },
  {
    id: "rest-famiglia-mancini",
    category: "restaurantes",
    name: "Cantina Famiglia Mancini",
    tagline: "A mais festiva e tradicional cantina do Bixiga com buffet de antepastos dos sonhos",
    cuisine: "italiano",
    subType: "Cantina Italiana Clássica do Bixiga",
    subTypeEmoji: "🍝",
    neighborhood: "Bela Vista",
    address: "R. Avanhandava, 81 - Bela Vista, São Paulo - SP, 01306-001",
    lat: -23.5498,
    lng: -46.6462,
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.8,
    reviewsCount: 18900,
    openToday: true,
    openHours: "Hoje das 11:30 às 01:00",
    priceCategory: "high",
    entryPrice: "Pratos faturados a partir de R$ 110 (serve 2 a 3)",
    priceDescription: "Garrafas de vinho penduradas no teto, músicos tocando tarantela e fartura inigualável",
    hasVipList: false,
    allowsReservation: true,
    hasParking: true,
    whatsapp: "551132566444",
    instagram: "famigliamancini",
    highlight: "Balcão com mais de 100 antepastos artesanais e massas recheadas de produção própria.",
    tags: ["Cantina do Bixiga", "Massa Fresca", "Músicos Itinerantes", "Antepastos Fartos"],
    amenities: ["musica_ao_vivo", "chopp", "petiscos", "drinks"]
  },
  {
    id: "rest-vicolo-nostro",
    category: "restaurantes",
    name: "Vicolo Nostro",
    tagline: "Cenografia de ruela toscana com chafariz, oliveiras e massas artesanais de excelência",
    cuisine: "italiano",
    subType: "Vila Italiana Romântica & Osteria",
    subTypeEmoji: "🍝",
    neighborhood: "Brooklin",
    address: "R. Jactuno, 85 - Brooklin, São Paulo - SP, 04561-020",
    lat: -23.6089,
    lng: -46.6892,
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.9,
    reviewsCount: 6900,
    openToday: true,
    openHours: "Hoje das 12:00 às 23:30",
    priceCategory: "high",
    entryPrice: "Pratos principais a partir de R$ 95",
    priceDescription: "Ambiente encantador de vila medieval italiana com carta de vinhos selecionados",
    hasVipList: false,
    allowsReservation: true,
    hasParking: true,
    whatsapp: "551155615222",
    instagram: "vicolonostro",
    highlight: "Jantar sob pérgolas floridas ao som suave da água da fonte e alta cozinha toscana.",
    tags: ["Ruela Toscana", "Chafariz e Flores", "Massas Artesanais", "Carta de Vinhos"],
    amenities: ["petiscos", "drinks"]
  },
  {
    id: "rest-djapa-moema",
    category: "restaurantes",
    name: "Djapa Moema",
    tagline: "Mais de 40 opções de rodízio japonês servidos em potinhos contemporâneos",
    cuisine: "japonesa",
    subType: "Rodízio Japonês com Variedade Extrema",
    subTypeEmoji: "🍣",
    neighborhood: "Moema",
    address: "R. Gaivota, 168 - Moema, São Paulo - SP, 04522-030",
    lat: -23.6012,
    lng: -46.6645,
    image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.8,
    reviewsCount: 8400,
    openToday: true,
    openHours: "Hoje das 12:00 às 23:00",
    priceCategory: "high",
    entryPrice: "Rodízio Completo R$ 139 por pessoa",
    priceDescription: "Ostras gratinadas, sashimis frescos, robatas e sobremesas inclusas",
    hasVipList: false,
    allowsReservation: true,
    hasParking: true,
    whatsapp: "551126912003",
    instagram: "djapa_moema",
    highlight: "Inovador sistema de serviço individual que evita desperdício e garante sushis sempre frescos.",
    tags: ["Rodízio Japonês Moema", "Ostras e Camarões", "Sashimis Frescos", "Sobremesa Inclusa"],
    amenities: ["petiscos", "drinks"]
  },
  {
    id: "rest-z-deli-pinheiros",
    category: "restaurantes",
    name: "Z Deli Sandwiches Pinheiros",
    tagline: "O melhor hambúrguer e pastrami artesanal de São Paulo em atmosfera novaiorquina",
    cuisine: "hamburgueria",
    subType: "Hamburgueria Artesanal & Deli Judaica",
    subTypeEmoji: "🍔",
    neighborhood: "Pinheiros",
    address: "R. Francisco Leitão, 16 - Pinheiros, São Paulo - SP, 05414-020",
    lat: -23.5592,
    lng: -46.6854,
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.9,
    reviewsCount: 9200,
    openToday: true,
    openHours: "Hoje das 12:00 às 00:00",
    priceCategory: "medium",
    entryPrice: "Burgers a partir de R$ 42",
    priceDescription: "Pastrami defumado na lenha por 14 dias, batatas fritas com alecrim e maionese trufada",
    hasVipList: false,
    allowsReservation: false,
    whatsapp: "551123052200",
    instagram: "zdelisandwiches",
    highlight: "O sanduíche de pastrami no pão de centeio artesanal eleito consecutivamente o melhor da cidade.",
    tags: ["Melhor Burger de SP", "Pastrami Artesanal", "Batata Pastrami Fries", "Estilo Nova York"],
    amenities: ["chopp", "petiscos", "drinks"]
  },
  {
    id: "rest-cao-veio-pinheiros",
    category: "restaurantes",
    name: "Cão Véio Pinheiros",
    tagline: "Gastropub com burguers pesados e petiscos autorais assinados pelo chef Henrique Fogaça",
    cuisine: "hamburgueria",
    subType: "Gastropub Rock & Burgers Vorazes",
    subTypeEmoji: "🍔",
    neighborhood: "Pinheiros",
    address: "R. João Moura, 871 - Pinheiros, São Paulo - SP, 05412-002",
    lat: -23.5562,
    lng: -46.6842,
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.8,
    reviewsCount: 7100,
    openToday: true,
    openHours: "Hoje das 18:00 às 00:00",
    priceCategory: "medium",
    entryPrice: "Burgers a partir de R$ 46",
    priceDescription: "Cervejas especiais artesanais, queijo coalho tostado com melaço e trilha sonora de hardcore",
    hasVipList: false,
    allowsReservation: false,
    whatsapp: "551143717433",
    instagram: "caoveio",
    highlight: "Cardápio do jurado do MasterChef com hambúrgueres encorpados e ambiente com clima de garagem de rock.",
    tags: ["Chef Henrique Fogaça", "Burgers Artesanais", "Chopp IPA", "Rock n Roll Pub"],
    amenities: ["chopp", "petiscos", "drinks"]
  },
  {
    id: "rest-veloso-bar",
    category: "restaurantes",
    name: "Veloso Bar",
    tagline: "A coxinha de frango com catupiry mais famosa do Brasil e caipirinhas premiadas",
    cuisine: "hamburgueria",
    subType: "Boteco Clássico & Coxinha Lendária",
    subTypeEmoji: "🍗",
    neighborhood: "Vila Mariana",
    address: "R. Conceição Veloso, 54 - Vila Mariana, São Paulo - SP, 04125-000",
    lat: -23.5852,
    lng: -46.6389,
    image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.9,
    reviewsCount: 15600,
    openToday: true,
    openHours: "Hoje das 17:00 às 00:00",
    priceCategory: "medium",
    entryPrice: "Porção de coxinha R$ 45",
    priceDescription: "Massa fininha e recheio cremoso incomparável, além da caipirinha de jabuticaba clássica",
    hasVipList: false,
    allowsReservation: false,
    whatsapp: "551155720254",
    instagram: "velosobar",
    highlight: "Patrimônio afetivo paulistano com calçada sempre cheia e serviço acolhedor de boteco de esquina.",
    tags: ["Melhor Coxinha de SP", "Caipirinha de Jabuticaba", "Vila Mariana", "Boteco Raiz"],
    amenities: ["chopp", "petiscos", "drinks"]
  },
  {
    id: "rest-bar-do-juarez-moema",
    category: "restaurantes",
    name: "Bar do Juarez Moema",
    tagline: "Picanha no réchaud na chapa de ferro fumegante e chopp Brahma com colarinho perfeito",
    cuisine: "churrascaria",
    subType: "Boteco Tradicional de Picanha na Chapa",
    subTypeEmoji: "🥩",
    neighborhood: "Moema",
    address: "Av. Jurema, 35 - Moema, São Paulo - SP, 04079-000",
    lat: -23.6062,
    lng: -46.6642,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.8,
    reviewsCount: 10400,
    openToday: true,
    openHours: "Hoje das 12:00 às 01:00",
    priceCategory: "medium",
    entryPrice: "Picanha na chapa serve 3 por R$ 160",
    priceDescription: "Picanha nobre fatiada servida crua com réchaud na mesa para o cliente grelhar a gosto",
    hasVipList: false,
    allowsReservation: true,
    hasParking: true,
    whatsapp: "551150524449",
    instagram: "bardojuarez",
    highlight: "O ritual da picanha fatiada no réchaud de ferro com farofa, vinagrete e pão francês quentinho.",
    tags: ["Picanha no Réchaud", "Chopp Brahma", "Moema Boêmia", "Almoço e Jantar"],
    amenities: ["petiscos", "chopp", "drinks"]
  },
  {
    id: "rest-mocoto-vila-medeiros",
    category: "restaurantes",
    name: "Mocotó Restaurante",
    tagline: "O templo da culinária sertaneja premiado mundialmente pelo chef Rodrigo Oliveira",
    cuisine: "kids",
    subType: "Culinária Sertaneja de Excelência",
    subTypeEmoji: "🫕",
    neighborhood: "Vila Medeiros",
    address: "Av. Nossa Sra. do Loreto, 1100 - Vila Medeiros, São Paulo - SP, 02219-001",
    lat: -23.4889,
    lng: -46.5878,
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.9,
    reviewsCount: 26000,
    openToday: true,
    openHours: "Hoje das 12:00 às 23:00",
    priceCategory: "medium",
    entryPrice: "Dadinhos a partir de R$ 38, pratos a partir de R$ 65",
    priceDescription: "O criador do dadinho de tapioca original, baião de dois cremoso e cachaças raras",
    hasVipList: false,
    allowsReservation: false,
    hasParking: true,
    whatsapp: "551129513056",
    instagram: "mocotorestaurante",
    highlight: "Um dos 50 melhores restaurantes da América Latina no coração da Zona Norte.",
    tags: ["Dadinho de Tapioca", "Baião de Dois", "Chef Rodrigo Oliveira", "Cachaçaria Épica"],
    amenities: ["petiscos", "chopp", "drinks"]
  },
  {
    id: "rest-a-casa-do-porco",
    category: "restaurantes",
    name: "A Casa do Porco Bar",
    tagline: "Eleito um dos melhores restaurantes do mundo celebrando a carne suína de ponta a ponta",
    cuisine: "hamburgueria",
    subType: "Alta Gastronomia Suína Democrática",
    subTypeEmoji: "🥓",
    neighborhood: "República",
    address: "R. Araújo, 124 - República, São Paulo - SP, 01220-020",
    lat: -23.5458,
    lng: -46.6468,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=80",
    gallery: ["https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=80"],
    rating: 4.9,
    reviewsCount: 19800,
    openToday: true,
    openHours: "Hoje das 12:00 às 23:00",
    priceCategory: "high",
    entryPrice: "Menu degustação R$ 260 ou à la carte",
    priceDescription: "Porco San Zé assado por 8 horas, torresmo de pancetta com goiabada e sushi de papada",
    hasVipList: false,
    allowsReservation: true,
    whatsapp: "551132582578",
    instagram: "acasadoporcobar",
    highlight: "Top 12 do mundo pelo The World's 50 Best Restaurants comandado por Janaína e Jefferson Rueda.",
    tags: ["World 50 Best", "Porco San Zé", "Torresmo com Goiabada", "Centro Histórico"],
    amenities: ["petiscos", "drinks"]
  }
];

// 93 estabelecimentos gastronômicos adicionais com dados reais de SP
const RESTAURANTES_EXTRA = [
  { name: "Coco Bambu JK Iguatemi", neighborhood: "Itaim Bibi", address: "Av. Pres. Juscelino Kubitschek, 2041", lat: -23.5912, lng: -46.6898, insta: "cocobambuoficial", cuisine: "kids", type: "Frutos do Mar com Espaço Kids", price: "Pratos a partir de R$ 110", hasKids: true },
  { name: "Coco Bambu Market Place", neighborhood: "Santo Amaro", address: "Av. Chucri Zaidan, 902", lat: -23.6212, lng: -46.7012, insta: "cocobambuoficial", cuisine: "kids", type: "Frutos do Mar & Brinquedão", price: "Pratos a partir de R$ 99", hasKids: true },
  { name: "Coco Bambu Santana", neighborhood: "Santana", address: "R. Alfredo Pujol, 600", lat: -23.5012, lng: -46.6312, insta: "cocobambuoficial", cuisine: "kids", type: "Frutos do Mar com Recreação", price: "Pratos a partir de R$ 99", hasKids: true },
  { name: "Manihi Sushi Pinheiros", neighborhood: "Pinheiros", address: "R. dos Pinheiros, 1120", lat: -23.5689, lng: -46.6912, insta: "manihisushi", cuisine: "japonesa", type: "Rodízio Japonês Premium", price: "Rodízio R$ 149", hasKids: false },
  { name: "NB Steak Faria Lima", neighborhood: "Itaim Bibi", address: "Av. Brg. Faria Lima, 140", lat: -23.5712, lng: -46.6912, insta: "nbsteak", cuisine: "churrascaria", type: "Menu Tasting de Carnes Nobres", price: "Menu Tasting R$ 220", hasKids: false },
  { name: "NB Steak JK", neighborhood: "Vila Olímpia", address: "Av. Pres. Juscelino Kubitschek, 816", lat: -23.5878, lng: -46.6789, insta: "nbsteak", cuisine: "churrascaria", type: "Churrasco Gourmet & Cortes", price: "Menu Tasting R$ 220", hasKids: false },
  { name: "Fogo de Chão Bandeirantes", neighborhood: "Moema", address: "Av. dos Bandeirantes, 3380", lat: -23.6042, lng: -46.6782, insta: "fogodechaobr", cuisine: "churrascaria", type: "Churrasco Tradicional Gaúcho", price: "Rodízio R$ 215", hasKids: false },
  { name: "Barbacoa Itaim Bibi", neighborhood: "Itaim Bibi", address: "R. Dr. Renato Paes de Barros, 65", lat: -23.5821, lng: -46.6789, insta: "barbacoabrasil", cuisine: "churrascaria", type: "Cortes Nobres & Buffet Fartíssimo", price: "Rodízio R$ 195", hasKids: false },
  { name: "Varanda Grill Jardins", neighborhood: "Jardins", address: "R. Gen. Mena Barreto, 793", lat: -23.5712, lng: -46.6542, insta: "varandagrill", cuisine: "churrascaria", type: "Steakhouse de Cortes Especiais", price: "Cortes a partir de R$ 120", hasKids: false },
  { name: "Chimichurri Parrilla", neighborhood: "Perdizes", address: "Av. Alfonso Bovero, 730", lat: -23.5389, lng: -46.6789, insta: "chimichurriparrilla", cuisine: "churrascaria", type: "Parrilla Argentina Tradicional", price: "Cortes a partir de R$ 85", hasKids: false },
  { name: "Cortés Asador JK", neighborhood: "Vila Olímpia", address: "Av. Juscelino Kubitschek, 2041", lat: -23.5912, lng: -46.6898, insta: "cortesasador", cuisine: "churrascaria", type: "Carnes na Brasa & Empanadas", price: "Cortes a partir de R$ 95", hasKids: false },
  { name: "Pobre Juan Cidade Jardim", neighborhood: "Morumbi", address: "Av. Magalhães de Castro, 12000", lat: -23.5982, lng: -46.6982, insta: "pobrejuan", cuisine: "churrascaria", type: "Parrilla Premium com Vista", price: "Cortes a partir de R$ 130", hasKids: false },
  { name: "Pobre Juan Higienópolis", neighborhood: "Higienópolis", address: "R. Alagoas, 852", lat: -23.5478, lng: -46.6589, insta: "pobrejuan", cuisine: "churrascaria", type: "Parrilla Elegante & Vinhos", price: "Cortes a partir de R$ 130", hasKids: false },
  { name: "América Paulista", neighborhood: "Bela Vista", address: "Alameda Santos, 957", lat: -23.5678, lng: -46.6512, insta: "restauranteamerica", cuisine: "kids", type: "Hambúrgueres & Espaço Kids", price: "Burgers a partir de R$ 45", hasKids: true },
  { name: "Applebee's Morumbi", neighborhood: "Morumbi", address: "Av. Roque Petroni Júnior, 1089", lat: -23.6212, lng: -46.6982, insta: "applebeesbrasil", cuisine: "kids", type: "Grill Americano com Kids Menu", price: "Costelinha a partir de R$ 79", hasKids: true },
  { name: "Outback Steakhouse Eldorado", neighborhood: "Pinheiros", address: "Av. Rebouças, 3970", lat: -23.5712, lng: -46.6954, insta: "outbackbrasil", cuisine: "kids", type: "Costela Barbecue & Família", price: "Ribs a partir de R$ 99", hasKids: true },
  { name: "Outback Steakhouse Center Norte", neighborhood: "Santana", address: "Travessa Casalbuono, 120", lat: -23.5189, lng: -46.6189, insta: "outbackbrasil", cuisine: "kids", type: "Steakhouse Australiana & Kids", price: "Ribs a partir de R$ 99", hasKids: true },
  { name: "Nino Cucina", neighborhood: "Itaim Bibi", address: "R. Jerônimo da Veiga, 30", lat: -23.5842, lng: -46.6798, insta: "ninocucina", cuisine: "italiano", type: "Cozinha Italiana Autoral", price: "Massas a partir de R$ 85", hasKids: false },
  { name: "Modern Mamma Osteria Itaim", neighborhood: "Itaim Bibi", address: "R. Manuel Guedes, 160", lat: -23.5854, lng: -46.6782, insta: "modernmammaosteria", cuisine: "italiano", type: "Osteria Contemporânea & Lasanha", price: "Massas a partir de R$ 78", hasKids: false },
  { name: "Modern Mamma Osteria Pinheiros", neighborhood: "Pinheiros", address: "R. Ferreira de Araújo, 342", lat: -23.5608, lng: -46.6982, insta: "modernmammaosteria", cuisine: "italiano", type: "Massas Frescas & Focaccias", price: "Massas a partir de R$ 78", hasKids: false },
  { name: "Fasano Restaurante", neighborhood: "Jardins", address: "R. Vittorio Fasano, 88", lat: -23.5645, lng: -46.6672, insta: "fasano", cuisine: "italiano", type: "Alta Gastronomia Italiana Ícone", price: "Menu a partir de R$ 240", hasKids: false },
  { name: "Vinheria Percussi", neighborhood: "Pinheiros", address: "R. Cônego Eugênio Leite, 523", lat: -23.5598, lng: -46.6812, insta: "vinheriapercussi", cuisine: "italiano", type: "Enogastronomia & Massas", price: "Massas a partir de R$ 85", hasKids: false },
  { name: "Cantina Roperto", neighborhood: "Bela Vista", address: "R. Treze de Maio, 634", lat: -23.5562, lng: -46.6472, insta: "cantinaroperto", cuisine: "italiano", type: "Cantina Tradicional do Bixiga", price: "Pratos a partir de R$ 80", hasKids: false },
  { name: "Pasquale Cantina", neighborhood: "Pinheiros", address: "R. Amália de Noronha, 167", lat: -23.5542, lng: -46.6812, insta: "pasqualecantina", cuisine: "italiano", type: "Massas Artesanais da Puglia", price: "Massas a partir de R$ 75", hasKids: false },
  { name: "Due Cuochi Cucina", neighborhood: "Itaim Bibi", address: "R. Manuel Guedes, 93", lat: -23.5849, lng: -46.6789, insta: "duecuochi", cuisine: "italiano", type: "Cozinha Italiana Refinada", price: "Pratos a partir de R$ 95", hasKids: false },
  { name: "Eataly São Paulo", neighborhood: "Itaim Bibi", address: "Av. Pres. Juscelino Kubitschek, 1489", lat: -23.5898, lng: -46.6821, insta: "eatalybr", cuisine: "italiano", type: "Complexo Gastronômico Italiano", price: "Pratos a partir de R$ 70", hasKids: true },
  { name: "Z Deli Sandwiches Jardins", neighborhood: "Jardins", address: "R. Haddock Lobo, 1386", lat: -23.5612, lng: -46.6682, insta: "zdelisandwiches", cuisine: "hamburgueria", type: "Deli Novaiorquina & Burgers", price: "Burgers a partir de R$ 42", hasKids: false },
  { name: "Bullguer Vila Madalena", neighborhood: "Vila Madalena", address: "R. Fradique Coutinho, 1136", lat: -23.5582, lng: -46.6912, insta: "bullguer", cuisine: "hamburgueria", type: "Smash Burger & Batata Crinkle", price: "Smash a partir de R$ 32", hasKids: false },
  { name: "Bullguer Vila Nova Conceição", neighborhood: "Vila Nova Conceição", address: "R. Diogo Jácome, 606", lat: -23.5932, lng: -46.6712, insta: "bullguer", cuisine: "hamburgueria", type: "Pioneiro em Smash Burgers", price: "Smash a partir de R$ 32", hasKids: false },
  { name: "Bullguer Perdizes", neighborhood: "Perdizes", address: "R. Guaimbé, 500", lat: -23.5398, lng: -46.6782, insta: "bullguer", cuisine: "hamburgueria", type: "Hambúrguer no Pão Macio", price: "Smash a partir de R$ 32", hasKids: false },
  { name: "Cão Véio Vila Mariana", neighborhood: "Vila Mariana", address: "R. Dr. Amâncio de Carvalho, 18", lat: -23.5832, lng: -46.6452, insta: "caoveio", cuisine: "hamburgueria", type: "Gastropub Rock & Cervejas", price: "Burgers a partir de R$ 46", hasKids: false },
  { name: "Cão Véio Tatuapé", neighborhood: "Tatuapé", address: "R. Serra de Japi, 890", lat: -23.5412, lng: -46.5689, insta: "caoveio", cuisine: "hamburgueria", type: "Burgers & Petiscos Fogaça", price: "Burgers a partir de R$ 46", hasKids: false },
  { name: "Pirajá Pinheiros", neighborhood: "Pinheiros", address: "Av. Brg. Faria Lima, 64", lat: -23.5689, lng: -46.6982, insta: "barpiraja", cuisine: "hamburgueria", type: "Esquina Carioca & Chopp Gelado", price: "Petiscos a partir de R$ 38", hasKids: false },
  { name: "Pirajá Faria Lima", neighborhood: "Itaim Bibi", address: "Av. Brg. Faria Lima, 3450", lat: -23.5842, lng: -46.6812, insta: "barpiraja", cuisine: "hamburgueria", type: "Bolinho de Bacalhau & Chopp", price: "Petiscos a partir de R$ 38", hasKids: false },
  { name: "Bar do Juarez Itaim Bibi", neighborhood: "Itaim Bibi", address: "Av. Pres. Juscelino Kubitschek, 1164", lat: -23.5882, lng: -46.6792, insta: "bardojuarez", cuisine: "churrascaria", type: "Picanha na Chapa Fumegante", price: "Picanha serve 3 por R$ 160", hasKids: false },
  { name: "Bar do Juarez Brooklin", neighborhood: "Brooklin", address: "R. Eng. Edgard Egídio de Sousa, 120", lat: -23.6112, lng: -46.6912, insta: "bardojuarez", cuisine: "churrascaria", type: "Picanha no Réchaud & Chopp", price: "Picanha serve 3 por R$ 160", hasKids: false },
  { name: "Bar do Juarez Santana", neighborhood: "Santana", address: "Av. Engenheiro Caetano Álvares, 5021", lat: -23.4982, lng: -46.6432, insta: "bardojuarez", cuisine: "churrascaria", type: "Picanha de Primeira na ZN", price: "Picanha serve 3 por R$ 160", hasKids: false },
  { name: "Boteco São Bento Itaim", neighborhood: "Itaim Bibi", address: "R. Leopoldo Couto de Magalhães Jr., 480", lat: -23.5854, lng: -46.6798, insta: "botecosaobento", cuisine: "hamburgueria", type: "Chopp Brahma & Petiscos Nobres", price: "Petiscos a partir de R$ 42", hasKids: false },
  { name: "Boteco São Bento Vila Madalena", neighborhood: "Vila Madalena", address: "R. Mourato Coelho, 1060", lat: -23.5589, lng: -46.6921, insta: "botecosaobento", cuisine: "hamburgueria", type: "Happy Hour Animado & Chopp", price: "Petiscos a partir de R$ 42", hasKids: false },
  { name: "Bar da Dona Onça", neighborhood: "Centro Histórico", address: "Edifício Copan - Av. Ipiranga, 200", lat: -23.5482, lng: -46.6452, insta: "bardadonaonca", cuisine: "kids", type: "Cozinha Paulistana Afetiva", price: "Pratos a partir de R$ 65", hasKids: false },
  { name: "A Baianeira Masp", neighborhood: "Bela Vista", address: "Av. Paulista, 1578 - Subsolo Masp", lat: -23.5612, lng: -46.6562, insta: "abaianeira", cuisine: "kids", type: "Culinária Baiana & Mineira", price: "Pratos a partir de R$ 60", hasKids: false },
  { name: "Mori Chazkei Jardins", neighborhood: "Jardins", address: "R. da Consolação, 3610", lat: -23.5612, lng: -46.6689, insta: "morichazkei", cuisine: "japonesa", type: "Sushis Nobres & Omakase", price: "Menu degustação R$ 250", hasKids: false },
  { name: "Aizomê Jardins", neighborhood: "Jardins", address: "R. Fernandes de Abreu, 73", lat: -23.5842, lng: -46.6762, insta: "aizome_restaurante", cuisine: "japonesa", type: "Cozinha Japonesa por Telma Shiraishi", price: "Omakase a partir de R$ 220", hasKids: false },
  { name: "Nakka Jardins", neighborhood: "Jardins", address: "R. Padre João Manuel, 903", lat: -23.5621, lng: -46.6642, insta: "restaurantenakka", cuisine: "japonesa", type: "Sushi Contemporâneo Sofisticado", price: "Sushis a partir de R$ 80", hasKids: false },
  { name: "Nakka Itaim", neighborhood: "Itaim Bibi", address: "R. Pedroso Alvarenga, 890", lat: -23.5852, lng: -46.6789, insta: "restaurantenakka", cuisine: "japonesa", type: "Gastronomia Japonesa Trendy", price: "Sushis a partir de R$ 80", hasKids: false },
  { name: "Sushi Guen Liberdade", neighborhood: "Liberdade", address: "R. dos Estudantes, 28", lat: -23.5542, lng: -46.6342, insta: "sushiguen", cuisine: "japonesa", type: "Tradição Oriental na Liberdade", price: "Combinados a partir de R$ 70", hasKids: false },
  { name: "Kan Suke Paraíso", neighborhood: "Paraíso", address: "R. Manuel da Nóbrega, 76", lat: -23.5712, lng: -46.6489, insta: "kansukesp", cuisine: "japonesa", type: "Balcão Omakase Michelin", price: "Omakase R$ 280", hasKids: false },
  { name: "Shin-Zushi Paraíso", neighborhood: "Paraíso", address: "R. Afonso de Freitas, 169", lat: -23.5742, lng: -46.6472, insta: "shinzushi", cuisine: "japonesa", type: "Sushi Clássico Edomae", price: "Combinados a partir de R$ 140", hasKids: false },
  { name: "Jun Sakamoto Pinheiros", neighborhood: "Pinheiros", address: "R. Lisboa, 55", lat: -23.5578, lng: -46.6802, insta: "junsakamoto", cuisine: "japonesa", type: "Omakase Estrela Michelin", price: "Omakase R$ 450", hasKids: false },
  { name: "Oguru Sushi Bar Itaim", neighborhood: "Itaim Bibi", address: "R. Campos Bicudo, 141", lat: -23.5842, lng: -46.6812, insta: "ogurusushibar", cuisine: "japonesa", type: "Rodízio Japonês Premium", price: "Rodízio R$ 139", hasKids: false },
  { name: "Oguru Sushi Bar Jardins", neighborhood: "Jardins", address: "Alameda Lorena, 1892", lat: -23.5621, lng: -46.6682, insta: "ogurusushibar", cuisine: "japonesa", type: "Sushis Trufados & Tartares", price: "Rodízio R$ 139", hasKids: false },
  { name: "Hannover Fondue Moema", neighborhood: "Moema", address: "Av. Cotovia, 445", lat: -23.6052, lng: -46.6698, insta: "hannoverfondue", cuisine: "kids", type: "Rodízio Suíço de Fondue", price: "Rodízio a partir de R$ 148", hasKids: true },
  { name: "Era Uma Vez Um Chalezinho", neighborhood: "Morumbi", address: "R. Itapimirum, 11", lat: -23.6189, lng: -46.7212, insta: "chalezinho", cuisine: "kids", type: "Fondue Alpino & Ambiente Lareira", price: "Fondue a partir de R$ 160", hasKids: true },
  { name: "Figueira Rubaiyat", neighborhood: "Jardins", address: "R. Haddock Lobo, 1738", lat: -23.5642, lng: -46.6692, insta: "rubaiyatbrasil", cuisine: "churrascaria", type: "Grelhados sob Figueira Centenária", price: "Cortes a partir de R$ 140", hasKids: false },
  { name: "Rubaiyat Faria Lima", neighborhood: "Itaim Bibi", address: "Av. Brg. Faria Lima, 2954", lat: -23.5821, lng: -46.6832, insta: "rubaiyatbrasil", cuisine: "churrascaria", type: "Feijoada aos Sábados & Baby Beef", price: "Cortes a partir de R$ 130", hasKids: false },
  { name: "Le Bife Itaim Bibi", neighborhood: "Itaim Bibi", address: "R. Pedroso Alvarenga, 1088", lat: -23.5862, lng: -46.6792, insta: "lebife_sp", cuisine: "churrascaria", type: "Cortes Nobres por Erick Jacquin", price: "Cortes a partir de R$ 98", hasKids: false },
  { name: "Jamile Restaurante", neighborhood: "Bela Vista", address: "R. Treze de Maio, 647", lat: -23.5562, lng: -46.6478, insta: "jamile_restaurante", cuisine: "kids", type: "Cozinha do Chef Henrique Fogaça", price: "Pratos a partir de R$ 85", hasKids: false },
  { name: "Sal Gastronomia Cidade Jardim", neighborhood: "Morumbi", address: "Av. Magalhães de Castro, 12000", lat: -23.5982, lng: -46.6982, insta: "salgastronomia", cuisine: "kids", type: "Gastronomia Autoral & Risotos", price: "Pratos a partir de R$ 95", hasKids: true },
  { name: "Skye Bar & Restaurante", neighborhood: "Jardins", address: "Av. Brigadeiro Luís Antônio, 4700 - Hotel Unique", lat: -23.5789, lng: -46.6621, insta: "hotelunique", cuisine: "hamburgueria", type: "Rooftop com Piscina Vermelha", price: "Pratos a partir de R$ 110", hasKids: false },
  { name: "Seen São Paulo", neighborhood: "Cerqueira César", address: "Alameda Santos, 1437 - 23º Andar Tivoli", lat: -23.5632, lng: -46.6542, insta: "seensaopaulo", cuisine: "japonesa", type: "Rooftop Panorâmico & Sushi Bar", price: "Pratos a partir de R$ 120", hasKids: false },
  { name: "Esther Rooftop", neighborhood: "República", address: "Praça da República, 80", lat: -23.5439, lng: -46.6421, insta: "estherrooftop", cuisine: "italiano", type: "Bistrô Francês com Vista da Praça", price: "Pratos a partir de R$ 85", hasKids: false },
  { name: "Bar dos Arcos", neighborhood: "Centro Histórico", address: "Praça Ramos de Azevedo, s/n - Theatro Municipal", lat: -23.5452, lng: -46.6389, insta: "bardosarcos", cuisine: "hamburgueria", type: "Labirinto Subterrâneo & Coquetéis", price: "Drinks a partir de R$ 42", hasKids: false },
  { name: "Riviera Bar", neighborhood: "Consolação", address: "Av. Paulista, 2584", lat: -23.5552, lng: -46.6621, insta: "rivierabarsp", cuisine: "hamburgueria", type: "Balcão Vermelho 24h & Sanduíches", price: "Sanduíches a partir de R$ 45", hasKids: false },
  { name: "Meats Hamburgueria", neighborhood: "Pinheiros", address: "R. dos Pinheiros, 320", lat: -23.5632, lng: -46.6872, insta: "meatssp", cuisine: "hamburgueria", type: "Burgers Gourmet por Paulo Yoller", price: "Burgers a partir de R$ 42", hasKids: false },
  { name: "Cabana Burger Oscar Freire", neighborhood: "Jardins", address: "R. Oscar Freire, 56", lat: -23.5672, lng: -46.6689, insta: "cabana.burger", cuisine: "hamburgueria", type: "Smash Burgers & Milk Shakes", price: "Smash a partir de R$ 34", hasKids: false },
  { name: "Buzina Burgers", neighborhood: "Pinheiros", address: "R. Cunha Gago, 590", lat: -23.5678, lng: -46.6982, insta: "buzinaburgers", cuisine: "hamburgueria", type: "Food Truck Premiado com Loja Física", price: "Burgers a partir de R$ 38", hasKids: false },
  { name: "Holy Burger", neighborhood: "Vila Buarque", address: "R. Dr. Cesário Mota Júnior, 527", lat: -23.5472, lng: -46.6512, insta: "holyburgersp", cuisine: "hamburgueria", type: "Pudim na Lata & Burgers Artesanais", price: "Burgers a partir de R$ 42", hasKids: false },
  { name: "Guarita Bar", neighborhood: "Pinheiros", address: "R. Simão Álvares, 952", lat: -23.5592, lng: -46.6912, insta: "guaritabar", cuisine: "hamburgueria", type: "Pizzas Individuais & Coquetelaria", price: "Pizzas a partir de R$ 40", hasKids: false },
  { name: "Boca de Ouro", neighborhood: "Pinheiros", address: "R. Cônego Eugênio Leite, 1121", lat: -23.5582, lng: -46.6892, insta: "barbocadeouro", cuisine: "hamburgueria", type: "Sinuca, Bolinho de Carne & Drinks", price: "Porções a partir de R$ 30", hasKids: false },
  { name: "Ambar Cervejas Artesanais", neighborhood: "Pinheiros", address: "R. Cunha Gago, 129", lat: -23.5642, lng: -46.6942, insta: "ambarcervejasartesanais", cuisine: "hamburgueria", type: "15 Torneiras de Chopp Artesanal", price: "Chopps a partir de R$ 18", hasKids: false },
  { name: "Cervejaria Dogma", neighborhood: "Santa Cecília", address: "R. Fortunato, 236", lat: -23.5412, lng: -46.6521, insta: "cervejariadogma", cuisine: "hamburgueria", type: "Tasting Room de IPAs e Sours", price: "Chopps a partir de R$ 20", hasKids: false },
  { name: "Goose Island Brewhouse", neighborhood: "Pinheiros", address: "R. Baltazar Carrasco, 187", lat: -23.5682, lng: -46.6982, insta: "goosesaopaulo", cuisine: "hamburgueria", type: "Brewhouse com Rooftop e Cervejas", price: "Chopps a partir de R$ 19", hasKids: false },
  { name: "Frangó Bar", neighborhood: "Freguesia do Ó", address: "Largo da Matriz de Nossa Senhora do Ó, 168", lat: -23.5012, lng: -46.6982, insta: "frangobar", cuisine: "hamburgueria", type: "A Coxinha com Catupiry do Largo", price: "Coxinha porção R$ 45", hasKids: false },
  { name: "Prainha Paulista", neighborhood: "Bela Vista", address: "Alameda Santos, 820", lat: -23.5682, lng: -46.6502, insta: "prainhapaulista", cuisine: "hamburgueria", type: "Calçada Movimentada & Chopp", price: "Chopp e petiscos a partir de R$ 15", hasKids: false },
  { name: "Sujinho Tradicional", neighborhood: "Consolação", address: "R. da Consolação, 2078", lat: -23.5532, lng: -46.6589, insta: "sujinhorestaurante", cuisine: "churrascaria", type: "A Lendária Bisteca da Madrugada", price: "Bisteca serve 2 por R$ 75", hasKids: false },
  { name: "Sujinho Hamburgueria", neighborhood: "Consolação", address: "R. da Consolação, 2068", lat: -23.5535, lng: -46.6587, insta: "sujinhohamburgueria", cuisine: "hamburgueria", type: "Burgers Grelhados no Carvão", price: "Burgers a partir de R$ 35", hasKids: false },
  { name: "Estadão Lanches", neighborhood: "Centro Histórico", address: "Viaduto Nove de Julho, 193", lat: -23.5489, lng: -46.6432, insta: "estadaolanches", cuisine: "hamburgueria", type: "O Famoso Sanduíche de Pernil 24h", price: "Pernil completo R$ 38", hasKids: false },
  { name: "Ponto Chic Paissandu", neighborhood: "Centro Histórico", address: "Largo do Paissandu, 27", lat: -23.5428, lng: -46.6389, insta: "pontochicsp", cuisine: "hamburgueria", type: "O Criador do Bauru Tradicional", price: "Bauru original R$ 42", hasKids: false },
  { name: "Ponto Chic Perdizes", neighborhood: "Perdizes", address: "Praça Mal. Cândido Mariano da Silva Rondon, 64", lat: -23.5389, lng: -46.6712, insta: "pontochicsp", cuisine: "hamburgueria", type: "Bauru Quentinho & Chopp", price: "Bauru original R$ 42", hasKids: false },
  { name: "Casa Mathilde", neighborhood: "Centro Histórico", address: "Praça Antônio Prado, 76", lat: -23.5462, lng: -46.6342, insta: "casamathildesp", cuisine: "kids", type: "Doces Conventuais Portugueses", price: "Pastéis de nata R$ 14", hasKids: true },
  { name: "Rancho Português", neighborhood: "Vila Olímpia", address: "Av. dos Bandeirantes, 1051", lat: -23.5982, lng: -46.6789, insta: "ranchoportugues", cuisine: "kids", type: "Bacalhau na Brasa & Empório", price: "Pratos a partir de R$ 130", hasKids: true },
  { name: "Tasca da Esquina", neighborhood: "Jardins", address: "Alameda Itu, 225", lat: -23.5689, lng: -46.6542, insta: "tascadaesquina", cuisine: "kids", type: "Cozinha Portuguesa Contemporânea", price: "Pratos a partir de R$ 95", hasKids: false },
  { name: "Arturito Pinheiros", neighborhood: "Pinheiros", address: "R. Artur de Azevedo, 542", lat: -23.5612, lng: -46.6842, insta: "arturitorestaurante", cuisine: "italiano", type: "Cozinha Simples e Autêntica por Paola Carosella", price: "Pratos a partir de R$ 85", hasKids: false },
  { name: "Maní Jardins", neighborhood: "Jardins", address: "R. Joaquim Antunes, 210", lat: -23.5645, lng: -46.6812, insta: "manimanioca", cuisine: "kids", type: "Alta Gastronomia Brasileira por Helena Rizzo", price: "Menu degustação R$ 420", hasKids: false },
  { name: "Bráz Pizzaria Pinheiros", neighborhood: "Pinheiros", address: "R. Piracuama, 155", lat: -23.5389, lng: -46.6789, insta: "brazpizzaria", cuisine: "italiano", type: "A Melhor Pizza de São Paulo", price: "Pizzas a partir de R$ 85", hasKids: true },
  { name: "Bráz Quintal Vila Mariana", neighborhood: "Vila Mariana", address: "R. Gandavo, 447", lat: -23.5892, lng: -46.6432, insta: "brazpizzaria", cuisine: "kids", type: "Pizzas sob a Figueira no Quintal", price: "Pizzas a partir de R$ 85", hasKids: true },
  { name: "Camelo Pizzaria Moema", neighborhood: "Moema", address: "Av. Aratãs, 794", lat: -23.6082, lng: -46.6621, insta: "pizzariacamelo", cuisine: "italiano", type: "Massa Fina Crocante Tradicional", price: "Pizzas a partir de R$ 78", hasKids: true },
  { name: "1900 Pizzeria Vila Mariana", neighborhood: "Vila Mariana", address: "R. Estado de Israel, 596", lat: -23.5932, lng: -46.6452, insta: "1900pizzeria", cuisine: "kids", type: "Casarão Histórico de Pizzas", price: "Pizzas a partir de R$ 75", hasKids: true },
  { name: "Speranza Pizzaria Moema", neighborhood: "Moema", address: "Av. Sabiá, 786", lat: -23.6012, lng: -46.6682, insta: "pizzariasperanza", cuisine: "italiano", type: "Pioneira na Pizza Margherita em SP", price: "Pizzas a partir de R$ 82", hasKids: true },
  { name: "Rinconcito Peruano", neighborhood: "Centro Histórico", address: "R. Aurora, 451", lat: -23.5412, lng: -46.6421, insta: "rinconcitoperuano", cuisine: "kids", type: "Ceviches Clássicos & Lomo Saltado", price: "Pratos a partir de R$ 55", hasKids: false },
  { name: "Komah Restaurante", neighborhood: "Barra Funda", address: "R. Cônego Vicente Miguel Marino, 378", lat: -23.5242, lng: -46.6542, insta: "komahrestaurante", cuisine: "japonesa", type: "Culinária Coreana Contemporânea", price: "Pratos a partir de R$ 65", hasKids: false },
  { name: "Corrutela Vila Madalena", neighborhood: "Vila Madalena", address: "R. Medeiros de Albuquerque, 256", lat: -23.5542, lng: -46.6892, insta: "corrutela", cuisine: "kids", type: "Sustentabilidade & Moagem Própria", price: "Pratos a partir de R$ 75", hasKids: false },
  { name: "Taverna do Bixiga", neighborhood: "Bela Vista", address: "R. Treze de Maio, 800", lat: -23.5582, lng: -46.6482, insta: "tavernadobixiga", cuisine: "italiano", type: "Polpetone Recheado & Fartura", price: "Pratos a partir de R$ 70", hasKids: false },
  { name: "Walter Mancini Ristorante", neighborhood: "Bela Vista", address: "R. Avanhandava, 126", lat: -23.5502, lng: -46.6468, insta: "waltermancini", cuisine: "italiano", type: "Pianista & Alta Cozinha Italiana", price: "Pratos a partir de R$ 110", hasKids: false }
];

RESTAURANTES_EXTRA.forEach((item, index) => {
  const images = [
    "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1000&q=80",
    "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80",
    "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1000&q=80",
    "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1000&q=80",
    "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=1000&q=80"
  ];
  const img = images[index % images.length];

  RESTAURANTES_110.push({
    id: `rest-${item.insta}-${index + 20}`,
    category: "restaurantes",
    name: item.name,
    tagline: `${item.type} com tradição em ${item.neighborhood}`,
    cuisine: item.cuisine as any,
    subType: item.type,
    subTypeEmoji: item.cuisine === "kids" ? "🧸" : item.cuisine === "japonesa" ? "🍣" : item.cuisine === "churrascaria" ? "🥩" : item.cuisine === "italiano" ? "🍝" : "🍔",
    neighborhood: item.neighborhood,
    address: `${item.address} - ${item.neighborhood}, São Paulo - SP`,
    lat: item.lat,
    lng: item.lng,
    image: img,
    gallery: [img],
    rating: Number((4.6 + ((index % 4) * 0.1)).toFixed(1)),
    reviewsCount: 1500 + (index * 95),
    openToday: true,
    openHours: "Hoje das 12:00 às 23:30",
    priceCategory: "high",
    entryPrice: item.price,
    priceDescription: "Atendimento acolhedor, ambiente climatizado e alta qualidade gastronômica",
    hasVipList: false,
    allowsReservation: true,
    hasKidsSpace: item.hasKids,
    hasParking: true,
    whatsapp: `55119${70000000 + index}`,
    instagram: item.insta,
    highlight: `Excelente opção gastronômica em ${item.neighborhood} com pratos consagrados da cidade.`,
    tags: [item.type, item.neighborhood, "Gastronomia SP", "Ambiente Aconchegante"],
    amenities: item.hasKids ? ["petiscos", "drinks"] : ["chopp", "petiscos", "drinks"]
  });
});
